// ------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本: 16.0.0.0
//  
//     对此文件的更改可能导致不正确的行为，如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace FileLoder.T_AdoNet
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\BugServiceTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class BugServiceTemplate : BugServiceTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("using System.Linq;\r\nusing ");
            
            #line 7 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\BugServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_projectName));
            
            #line default
            #line hidden
            this.Write(".Model;\r\nusing ");
            
            #line 8 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\BugServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_projectName));
            
            #line default
            #line hidden
            this.Write(".IDAL.");
            
            #line 8 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\BugServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityName));
            
            #line default
            #line hidden
            this.Write(";\r\nusing System.Collections.Generic;\r\nusing System.Data.SqlClient;\r\nusing System." +
                    "Text;\r\nusing System.Data;\r\nusing System;\r\n\r\nnamespace ");
            
            #line 15 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\BugServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_projectName));
            
            #line default
            #line hidden
            this.Write(".Service.");
            
            #line 15 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\BugServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityName));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n\t");
            
            #line 17 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\BugServiceTemplate.tt"
 var PKData=_Columns.Where(t=>t.PK==true).FirstOrDefault();
		if(PKData==null) throw new Exception("未包含主键字段");
	
            
            #line default
            #line hidden
            this.Write("\t/// <summary>\r\n\t/// 数据访问类:");
            
            #line 21 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\BugServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityName));
            
            #line default
            #line hidden
            this.Write("\r\n\t/// </summary>\r\n\tpublic partial class ");
            
            #line 23 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\BugServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityName));
            
            #line default
            #line hidden
            this.Write("\r\n\t{\r\n\t\t/// <summary>\r\n\t\t/// 得到最大ID\r\n\t\t/// </summary>\r\n\t\tpublic int GetMaxId()\r\n\t" +
                    "\t{\r\n            return DbHelperSQL.GetMaxID(\"");
            
            #line 30 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\BugServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PKData.Code));
            
            #line default
            #line hidden
            this.Write("\", \"");
            
            #line 30 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\BugServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityName));
            
            #line default
            #line hidden
            this.Write("\"); \r\n\t\t}\r\n\t\t/// <summary>\r\n\t\t/// 是否存在该记录\r\n\t\t/// </summary>\r\n\t\tpublic bool Exists" +
                    "(");
            
            #line 35 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\BugServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PKData.CodeType));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 35 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\BugServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PKData.Code));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t{\r\n\t\t\tStringBuilder strSql=new StringBuilder();\r\n\t\t\tstrSql.Append(\"select co" +
                    "unt(1) from ");
            
            #line 38 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\BugServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityName));
            
            #line default
            #line hidden
            this.Write("\");\r\n\t\t\tstrSql.Append(\" where ");
            
            #line 39 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\BugServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PKData.Code));
            
            #line default
            #line hidden
            this.Write("=@");
            
            #line 39 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\BugServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PKData.Code));
            
            #line default
            #line hidden
            this.Write("\");\r\n            List<SqlParameter> Para = new List<SqlParameter>();\r\n\t\t\tPara.Add" +
                    "(new SqlParameter(\"@");
            
            #line 41 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\BugServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PKData.Code));
            
            #line default
            #line hidden
            this.Write("\", ");
            
            #line 41 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\BugServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PKData.Code));
            
            #line default
            #line hidden
            this.Write("));\r\n\t\t\treturn DbHelperSQL.Exists(strSql.ToString(),Para.ToArray());\r\n\t\t}\r\n\t\tpubl" +
                    "ic int Add(Model.");
            
            #line 44 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\BugServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityName));
            
            #line default
            #line hidden
            this.Write(" m");
            
            #line 44 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\BugServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityName.ToLower()));
            
            #line default
            #line hidden
            this.Write(@")
		{
			string flag = ""insert into {0} ({1}) values ({2}) ;select @@IDENTITY"";
            StringBuilder Key = new StringBuilder();
            StringBuilder Values = new StringBuilder();
            List<SqlParameter> Para = new List<SqlParameter>();
			");
            
            #line 50 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\BugServiceTemplate.tt"
 foreach(var item in _Columns.Where(t=>t.PK!=true)){
            
            #line default
            #line hidden
            this.Write("\t\t\tif(m");
            
            #line 51 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\BugServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityName.ToLower()));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 51 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\BugServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code));
            
            #line default
            #line hidden
            this.Write("!=null)\r\n\t\t\t{\r\n\t\t\t\t");
            
            #line 53 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\BugServiceTemplate.tt"
 if(!item.PK) {
            
            #line default
            #line hidden
            this.Write("\t\t\t\tKey.Append(\",");
            
            #line 54 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\BugServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code));
            
            #line default
            #line hidden
            this.Write("\");\r\n\t\t\t\tValues.Append(\",@");
            
            #line 55 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\BugServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code));
            
            #line default
            #line hidden
            this.Write("\");\r\n\t\t\t\tPara.Add(new SqlParameter(\"@");
            
            #line 56 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\BugServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code));
            
            #line default
            #line hidden
            this.Write("\", m");
            
            #line 56 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\BugServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityName.ToLower()));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 56 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\BugServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code));
            
            #line default
            #line hidden
            this.Write("));\r\n\t\t\t\t");
            
            #line 57 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\BugServiceTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("\t\t\t}\r\n\t\t\t");
            
            #line 59 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\BugServiceTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("\t\t\tvar Sql=string.Format(flag,\"");
            
            #line 60 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\BugServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityName));
            
            #line default
            #line hidden
            this.Write(@""",Key.ToString().Substring(1),Values.ToString().Substring(1));
			object obj = DbHelperSQL.GetSingle(Sql, Para.ToArray());
            if (obj == null)
            {
                return 1;
            }
            else
            {
                return Convert.ToInt32(obj);
            }
		}
		
		public bool Update(Model.");
            
            #line 72 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\BugServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityName));
            
            #line default
            #line hidden
            this.Write(" m");
            
            #line 72 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\BugServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityName.ToLower()));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t{\r\n\t\t\tStringBuilder Key = new StringBuilder();\r\n            List<SqlParamete" +
                    "r> Para = new List<SqlParameter>();\r\n            var flag=\"update ");
            
            #line 76 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\BugServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityName));
            
            #line default
            #line hidden
            this.Write(" set \";\r\n\t\t\t");
            
            #line 77 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\BugServiceTemplate.tt"
 var str="";foreach(var item in _Columns){
            
            #line default
            #line hidden
            this.Write("\t\t\tif(m");
            
            #line 78 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\BugServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityName.ToLower()));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 78 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\BugServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code));
            
            #line default
            #line hidden
            this.Write("!=null)\r\n\t\t\t{\r\n\t\t\t\t");
            
            #line 80 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\BugServiceTemplate.tt"
 if(item.PK) {
				str=" where "+item.Code+"=@"+item.Code;
				
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\tPara.Add(new SqlParameter(\"@");
            
            #line 83 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\BugServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code));
            
            #line default
            #line hidden
            this.Write("\", m");
            
            #line 83 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\BugServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityName.ToLower()));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 83 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\BugServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code));
            
            #line default
            #line hidden
            this.Write("));\r\n\t\t\t\t");
            
            #line 84 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\BugServiceTemplate.tt"
}else{
            
            #line default
            #line hidden
            this.Write("\t\t\t\tKey.Append(string.Format(\",");
            
            #line 85 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\BugServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code));
            
            #line default
            #line hidden
            this.Write("=@");
            
            #line 85 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\BugServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code));
            
            #line default
            #line hidden
            this.Write("\"));\r\n\t\t\t\tPara.Add(new SqlParameter(\"@");
            
            #line 86 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\BugServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code));
            
            #line default
            #line hidden
            this.Write("\", m");
            
            #line 86 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\BugServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityName.ToLower()));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 86 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\BugServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code));
            
            #line default
            #line hidden
            this.Write("));\r\n\t\t\t\t");
            
            #line 87 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\BugServiceTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("\t\t\t}\r\n\t\t\t");
            
            #line 89 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\BugServiceTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("\t\t\tKey.Append(\"");
            
            #line 90 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\BugServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(str));
            
            #line default
            #line hidden
            this.Write("\");\r\n\t\t\tint rowsAffected = DbHelperSQL.ExecuteSql(flag + Key.ToString().Substring" +
                    "(1), Para.ToArray());\r\n\t\t\tif (rowsAffected > 0)\r\n\t\t\t{\r\n\t\t\t\treturn true;\r\n\t\t\t}\r\n\t" +
                    "\t\telse\r\n\t\t\t{\r\n\t\t\t\treturn false;\r\n\t\t\t}\r\n\t\t}\r\n\t\tpublic int Delete(");
            
            #line 101 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\BugServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PKData.CodeType));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 101 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\BugServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PKData.Code));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t{\r\n\t\t\tStringBuilder strSql = new StringBuilder();\r\n\t\t\tList<SqlParameter> Par" +
                    "a = new List<SqlParameter>();\r\n            strSql.Append(\"delete from ");
            
            #line 105 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\BugServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityName));
            
            #line default
            #line hidden
            this.Write(" \");\r\n\t\t\tstrSql.Append(\" where ");
            
            #line 106 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\BugServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PKData.Code));
            
            #line default
            #line hidden
            this.Write("=@");
            
            #line 106 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\BugServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PKData.Code));
            
            #line default
            #line hidden
            this.Write(" \");\r\n\t\t\tPara.Add(new SqlParameter(\"@");
            
            #line 107 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\BugServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PKData.Code));
            
            #line default
            #line hidden
            this.Write("\", ");
            
            #line 107 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\BugServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PKData.Code));
            
            #line default
            #line hidden
            this.Write("));\r\n            return DbHelperSQL.ExecuteSql(strSql.ToString(), Para.ToArray())" +
                    ";\r\n\t\t}\r\n\t\t/// <summary>\r\n\t\t/// 批量删除数据\r\n\t\t/// </summary>\r\n\t\tpublic bool DeleteLis" +
                    "t(string ");
            
            #line 113 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\BugServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PKData.Code));
            
            #line default
            #line hidden
            this.Write("list)\r\n\t\t{\r\n\t\t\tStringBuilder strSql=new StringBuilder();\r\n\t\t\tstrSql.Append(\"delet" +
                    "e from ");
            
            #line 116 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\BugServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityName));
            
            #line default
            #line hidden
            this.Write(" \");\r\n\t\t\tstrSql.Append(\" where ");
            
            #line 117 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\BugServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PKData.Code));
            
            #line default
            #line hidden
            this.Write(" in (@");
            
            #line 117 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\BugServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PKData.Code));
            
            #line default
            #line hidden
            this.Write("list)  \");\r\n\t\t\tList<SqlParameter> Para = new List<SqlParameter>();\r\n\t\t\tPara.Add(n" +
                    "ew SqlParameter(\"@");
            
            #line 119 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\BugServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PKData.Code));
            
            #line default
            #line hidden
            this.Write("list\", ");
            
            #line 119 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\BugServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PKData.Code));
            
            #line default
            #line hidden
            this.Write("list));\r\n\t\t\tint rows=DbHelperSQL.ExecuteSql(strSql.ToString(), Para.ToArray());\r\n" +
                    "\t\t\tif (rows > 0)\r\n\t\t\t{\r\n\t\t\t\treturn true;\r\n\t\t\t}\r\n\t\t\telse\r\n\t\t\t{\r\n\t\t\t\treturn false;" +
                    "\r\n\t\t\t}\r\n\t\t}\r\n\t\tpublic Model.");
            
            #line 130 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\BugServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityName));
            
            #line default
            #line hidden
            this.Write(" GetModel(");
            
            #line 130 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\BugServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PKData.CodeType));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 130 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\BugServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PKData.Code));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t{\r\n\t\t\tStringBuilder strSql = new StringBuilder();\r\n\t\t\tList<SqlParameter> Par" +
                    "a = new List<SqlParameter>();\r\n            strSql.Append(\"select * from ");
            
            #line 134 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\BugServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityName));
            
            #line default
            #line hidden
            this.Write(" \");\r\n\t\t\tstrSql.Append(\" where ");
            
            #line 135 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\BugServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PKData.Code));
            
            #line default
            #line hidden
            this.Write("=@");
            
            #line 135 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\BugServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PKData.Code));
            
            #line default
            #line hidden
            this.Write(" \");\r\n\t\t\tPara.Add(new SqlParameter(\"@");
            
            #line 136 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\BugServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PKData.Code));
            
            #line default
            #line hidden
            this.Write("\", ");
            
            #line 136 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\BugServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PKData.Code));
            
            #line default
            #line hidden
            this.Write("));\r\n            DataSet ds= DbHelperSQL.Query(strSql.ToString(), Para.ToArray())" +
                    ";\r\n\t\t\tif (ds.Tables.Count > 0&&ds.Tables[0].Rows.Count > 0)\r\n\t\t\t{\r\n\t\t\t\treturn Ro" +
                    "wToModel(ds.Tables[0].Rows[0]);\r\n\t\t\t}\r\n\t\t\treturn null;\r\n\t\t}\r\n\t\tpublic Model.");
            
            #line 144 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\BugServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityName));
            
            #line default
            #line hidden
            this.Write(" RowToModel(DataRow row)\r\n\t\t{\r\n\t\t\tModel.");
            
            #line 146 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\BugServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityName));
            
            #line default
            #line hidden
            this.Write(" m");
            
            #line 146 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\BugServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityName));
            
            #line default
            #line hidden
            this.Write("=new Model.");
            
            #line 146 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\BugServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityName));
            
            #line default
            #line hidden
            this.Write("();\r\n\t\t\t");
            
            #line 147 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\BugServiceTemplate.tt"
 foreach(var item in _Columns){if(item.CodeType=="string"){
            
            #line default
            #line hidden
            this.Write("\t\t\tif(row[\"");
            
            #line 148 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\BugServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code));
            
            #line default
            #line hidden
            this.Write("\"]!=null)\r\n\t\t\t\tm");
            
            #line 149 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\BugServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityName));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 149 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\BugServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code));
            
            #line default
            #line hidden
            this.Write("=row[\"");
            
            #line 149 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\BugServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code));
            
            #line default
            #line hidden
            this.Write("\"].ToString();\r\n\t\t\t");
            
            #line 150 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\BugServiceTemplate.tt"
}else{
            
            #line default
            #line hidden
            this.Write("\t\t\tif(row[\"");
            
            #line 151 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\BugServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code));
            
            #line default
            #line hidden
            this.Write("\"]!=null)\r\n\t\t\t\tm");
            
            #line 152 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\BugServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityName));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 152 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\BugServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code));
            
            #line default
            #line hidden
            this.Write("=");
            
            #line 152 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\BugServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.CodeType.Replace("?","")));
            
            #line default
            #line hidden
            this.Write(".Parse(row[\"");
            
            #line 152 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\BugServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code));
            
            #line default
            #line hidden
            this.Write("\"].ToString());\r\n\t\t\t");
            
            #line 153 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\BugServiceTemplate.tt"
}}
            
            #line default
            #line hidden
            this.Write("\t\t\treturn m");
            
            #line 154 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\BugServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityName));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t}\r\n\t\t/// <summary>\r\n\t\t/// 获得数据列表\r\n\t\t/// </summary>\r\n        public DataSet G" +
                    "etList(string strWhere, List<SqlParameter> para = null)\r\n\t\t{\r\n\t\t\tStringBuilder s" +
                    "trSql=new StringBuilder();\r\n\t\t\tstrSql.Append(\"select * \");\r\n\t\t\tstrSql.Append(\" F" +
                    "ROM ");
            
            #line 163 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\BugServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityName));
            
            #line default
            #line hidden
            this.Write(@" "");
			if(strWhere.Trim()!="""")
			{
				strSql.Append("" where ""+strWhere);
            }
            return para == null ? DbHelperSQL.Query(strSql.ToString()) : DbHelperSQL.Query(strSql.ToString(), para.ToArray());
		}
		/// <summary>
		/// 获得前几行数据
		/// </summary>
		public DataSet GetList(int Top, string strWhere, string filedOrder, List<SqlParameter> para = null)
		{
			StringBuilder strSql=new StringBuilder();
			strSql.Append(""select "");
			if(Top>0)
			{
				strSql.Append("" top ""+Top.ToString());
			}
			strSql.Append("" * "");
			strSql.Append("" FROM ");
            
            #line 182 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\BugServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityName));
            
            #line default
            #line hidden
            this.Write(@" "");
			if(strWhere.Trim()!="""")
			{
				strSql.Append("" where ""+strWhere);
			}
            strSql.Append("" order by "" + filedOrder);
            return para == null ? DbHelperSQL.Query(strSql.ToString()) : DbHelperSQL.Query(strSql.ToString(), para.ToArray());
		}
		public int GetRecordCount(string strWhere=null, List<SqlParameter> para = null)
        {
            StringBuilder strSql = new StringBuilder();
            strSql.Append(""select count(1) FROM ");
            
            #line 193 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\BugServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityName));
            
            #line default
            #line hidden
            this.Write(@" "");
            if (strWhere!=null&&strWhere.Trim()!="""")
            {
                strSql.Append("" where "" + strWhere);
            }
            object obj =para==null? DbHelperSQL.GetSingle(strSql.ToString()):DbHelperSQL.GetSingle(strSql.ToString(),para.ToArray());
            if (obj == null)
            {
                return 0;
            }
            else
            {
                return Convert.ToInt32(obj);
            }
        }
		/// <summary>
		/// 分页获取数据列表
		/// </summary>
        public DataSet GetListByPage(string strWhere, string orderby, int startIndex, int endIndex, List<SqlParameter> para = null)
		{
			StringBuilder strSql=new StringBuilder();
			strSql.Append(""SELECT * FROM ( "");
			strSql.Append("" SELECT ROW_NUMBER() OVER ("");
			if (!string.IsNullOrEmpty(orderby.Trim()))
			{
				strSql.Append(""order by T."" + orderby );
			}
			else
			{
				strSql.Append(""order by T.ID desc"");
			}
			strSql.Append("")AS Row, T.*  from ");
            
            #line 224 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\BugServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityName));
            
            #line default
            #line hidden
            this.Write(@" T "");
			if (!string.IsNullOrEmpty(strWhere.Trim()))
			{
				strSql.Append("" WHERE "" + strWhere);
			}
			strSql.Append("" ) TT"");
			strSql.AppendFormat("" WHERE TT.Row between {0} and {1}"", startIndex, endIndex);
            return para == null ? DbHelperSQL.Query(strSql.ToString()) : DbHelperSQL.Query(strSql.ToString(), para.ToArray());
		}
        public DataSet GetListByPage(string strSql, List<SqlParameter> para = null)
        {
            return para == null ? DbHelperSQL.Query(strSql) : DbHelperSQL.Query(strSql, para.ToArray());
        }
	}
}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public class BugServiceTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
