// ------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本: 16.0.0.0
//  
//     对此文件的更改可能导致不正确的行为，如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace FileLoder.T_DotnetCore
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using FileLoder.TemplateModel;
    using FileLoder.Helper;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class CoreBaseServiceTemplate : CoreBaseServiceTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("\r\n");
            
            #line 9 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
 var orderNames = new List<string>(); 
            
            #line default
            #line hidden
            this.Write("using System.Linq.Expressions;\r\nusing System.Threading.Tasks;\r\nusing System;\r\nusi" +
                    "ng System.Linq;\r\nusing Edu.Core.Data;\r\nusing ");
            
            #line 15 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_projectName));
            
            #line default
            #line hidden
            this.Write(".Entity;\r\nusing ");
            
            #line 16 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_projectName));
            
            #line default
            #line hidden
            this.Write(".Base;\r\nusing ");
            
            #line 17 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_projectName));
            
            #line default
            #line hidden
            this.Write(".Models;\r\nusing System.Collections.Generic;\r\nusing Edu.Core.Handler;\r\nusing Edu.C" +
                    "ore.Site;\r\nusing Edu.Core.Extend;\r\nusing Edu.Core.Model;\r\nusing System.Data;\r\n\r\n" +
                    "");
            
            #line 25 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
 var PKData=models.ColumnsList.Where(t=>t.PK==true).FirstOrDefault();
	if(PKData==null) throw new Exception("未包含主键字段");
	var IsFK=PKData.FK;

            
            #line default
            #line hidden
            this.Write("\r\nnamespace ");
            
            #line 30 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_projectName));
            
            #line default
            #line hidden
            this.Write(".BaseService\r\n{\r\n\tpublic class ");
            
            #line 32 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityName));
            
            #line default
            #line hidden
            this.Write("BaseService : I");
            
            #line 32 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityName));
            
            #line default
            #line hidden
            this.Write("BaseService\r\n\t{\r\n\t\tprivate readonly ");
            
            #line 34 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_repositoryText));
            
            #line default
            #line hidden
            this.Write("<");
            
            #line 34 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityName));
            
            #line default
            #line hidden
            this.Write("Entity> _");
            
            #line 34 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityName.ToLower()));
            
            #line default
            #line hidden
            this.Write("Repository;\r\n        private readonly IWorkContext _workContext;\r\n        private" +
                    " readonly IValidateCode _validateCode;\r\n\r\n\t\tpublic ");
            
            #line 38 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityName));
            
            #line default
            #line hidden
            this.Write("BaseService(");
            
            #line 38 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_repositoryText));
            
            #line default
            #line hidden
            this.Write("<");
            
            #line 38 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityName));
            
            #line default
            #line hidden
            this.Write("Entity> ");
            
            #line 38 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityName.ToLower()));
            
            #line default
            #line hidden
            this.Write("Repository, IWorkContext workContext,IValidateCode validateCode)\r\n\t\t{\r\n\t\t\t_");
            
            #line 40 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityName.ToLower()));
            
            #line default
            #line hidden
            this.Write("Repository = ");
            
            #line 40 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityName.ToLower()));
            
            #line default
            #line hidden
            this.Write("Repository;\r\n\t\t\t_workContext=workContext;\r\n            _validateCode = validateCo" +
                    "de;\r\n\t\t}\r\n\r\n\t\t\r\n\t\tpublic IQueryable<");
            
            #line 46 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityName));
            
            #line default
            #line hidden
            this.Write("Entity> Where(Expression<Func<");
            
            #line 46 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityName));
            
            #line default
            #line hidden
            this.Write("Entity, bool>> expression=null,IQueryable<");
            
            #line 46 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityName));
            
            #line default
            #line hidden
            this.Write("Entity> Query=null)\r\n\t\t{\r\n\t\t\t\r\n\t\t}\r\n\t\t\r\n\t\tpublic IQueryable<");
            
            #line 51 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityName));
            
            #line default
            #line hidden
            this.Write("Entity> SearchByCondition(");
            
            #line 51 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityName));
            
            #line default
            #line hidden
            this.Write("SearchCondition condition,Expression<Func<");
            
            #line 51 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityName));
            
            #line default
            #line hidden
            this.Write("Entity, bool>> expression=null,IQueryable<");
            
            #line 51 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityName));
            
            #line default
            #line hidden
            this.Write("Entity> Query=null)\r\n\t\t{\r\n\t\t\tvar query = Where(expression,Query);\r\n\t\t\t#region 一级数" +
                    "据动态字段查询\r\n\t\t\tif(condition!=null)\r\n\t\t\t{\r\n");
            
            #line 57 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
 foreach(var model in _sModels.Where(r=>r.Virtual==false).OrderByDescending(c => c.Search)){ 
if(model.Search == SearchType.Range){
            
            #line default
            #line hidden
            this.Write("\t\t\t\tif (condition.");
            
            #line 59 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Code));
            
            #line default
            #line hidden
            this.Write("Begin.HasValue)\r\n\t\t\t\t{\r\n\t\t\t\t\t");
            
            #line 61 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
if(model.CodeType.StartsWith("DateTime")){
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\tvar ");
            
            #line 62 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Code));
            
            #line default
            #line hidden
            this.Write("Begin=condition.");
            
            #line 62 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Code));
            
            #line default
            #line hidden
            this.Write("Begin.Begin();\r\n\t\t\t\t\tquery = query.Where(q => q.");
            
            #line 63 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Code));
            
            #line default
            #line hidden
            this.Write(">= ");
            
            #line 63 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Code));
            
            #line default
            #line hidden
            this.Write("Begin);\r\n\t\t\t\t\t");
            
            #line 64 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
}else{
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\tquery = query.Where(q => q.");
            
            #line 65 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Code));
            
            #line default
            #line hidden
            this.Write(">= condition.");
            
            #line 65 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Code));
            
            #line default
            #line hidden
            this.Write("Begin);\r\n\t\t\t\t\t");
            
            #line 66 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("\t\t\t\t}\r\n\t\t\t\tif (condition.");
            
            #line 68 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Code));
            
            #line default
            #line hidden
            this.Write("End.HasValue)\r\n\t\t\t\t{\r\n\t\t\t\t\t");
            
            #line 70 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
if(model.CodeType.StartsWith("DateTime")){
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\tvar ");
            
            #line 71 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Code));
            
            #line default
            #line hidden
            this.Write("End=condition.");
            
            #line 71 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Code));
            
            #line default
            #line hidden
            this.Write("End.End();\r\n\t\t\t\t\t\tquery = query.Where(q => q.");
            
            #line 72 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Code));
            
            #line default
            #line hidden
            this.Write(" <= ");
            
            #line 72 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Code));
            
            #line default
            #line hidden
            this.Write("End);\r\n\t\t\t\t\t");
            
            #line 73 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
}else{
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\tquery = query.Where(q => q.");
            
            #line 74 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Code));
            
            #line default
            #line hidden
            this.Write(">= condition.");
            
            #line 74 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Code));
            
            #line default
            #line hidden
            this.Write("End);\r\n\t\t\t\t\t");
            
            #line 75 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("\t\t\t\t}\r\n");
            
            #line 77 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
 }else if(model.Search == SearchType.Equal){
	if(model.CodeType =="string"){
            
            #line default
            #line hidden
            this.Write("\t\t\t\tif (!string.IsNullOrEmpty(condition.");
            
            #line 79 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Code));
            
            #line default
            #line hidden
            this.Write("))\r\n\t\t\t\t\tquery = query.Where(q => q.");
            
            #line 80 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Code));
            
            #line default
            #line hidden
            this.Write(" == condition.");
            
            #line 80 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Code));
            
            #line default
            #line hidden
            this.Write(");\r\n\t");
            
            #line 81 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
} else if(model.CodeType =="Guid"){
            
            #line default
            #line hidden
            this.Write("\t\t\t\tif (condition.");
            
            #line 82 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Code));
            
            #line default
            #line hidden
            this.Write("!=Guid.Empty)\r\n\t\t\t\t\tquery = query.Where(q => q.");
            
            #line 83 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Code));
            
            #line default
            #line hidden
            this.Write(" == condition.");
            
            #line 83 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Code));
            
            #line default
            #line hidden
            this.Write(");\r\n\t");
            
            #line 84 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
}else{
            
            #line default
            #line hidden
            this.Write("\t\t\t\tif (condition.");
            
            #line 85 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Code));
            
            #line default
            #line hidden
            this.Write(".HasValue)\r\n\t\t\t\t\tquery = query.Where(q => ");
            
            #line 86 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((model.EM==true?"(int)":"")));
            
            #line default
            #line hidden
            this.Write("q.");
            
            #line 86 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Code));
            
            #line default
            #line hidden
            this.Write(" == condition.");
            
            #line 86 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Code));
            
            #line default
            #line hidden
            this.Write(".Value);\r\n\t");
            
            #line 87 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
 }
} else if(model.Search == SearchType.Like){
			if(model.CodeType =="string"){
            
            #line default
            #line hidden
            this.Write("\t\t\t\tif (!string.IsNullOrEmpty(condition.");
            
            #line 90 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Code));
            
            #line default
            #line hidden
            this.Write("))\r\n\t\t\t\t\tquery = query.Where(q => q.");
            
            #line 91 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Code));
            
            #line default
            #line hidden
            this.Write(".Contains(condition.");
            
            #line 91 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Code));
            
            #line default
            #line hidden
            this.Write("));\r\n\t\t\t");
            
            #line 92 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
}else{
            
            #line default
            #line hidden
            this.Write("\t\t\t\tif (condition.");
            
            #line 93 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Code));
            
            #line default
            #line hidden
            this.Write(".HasValue)\r\n\t\t\t\t\tquery = query.Where(q => q.");
            
            #line 94 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Code));
            
            #line default
            #line hidden
            this.Write(".Contains(condition.");
            
            #line 94 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Code));
            
            #line default
            #line hidden
            this.Write(".Value));\r\n");
            
            #line 95 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
}} else if(model.Search == SearchType.In){
            
            #line default
            #line hidden
            this.Write("\t\t\t\tif (condition.");
            
            #line 96 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Code));
            
            #line default
            #line hidden
            this.Write("s != null && condition.");
            
            #line 96 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Code));
            
            #line default
            #line hidden
            this.Write("s.Any())\r\n");
            
            #line 97 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
if(model.IsNull){
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\tquery = query.Where(q =>q.");
            
            #line 98 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Code));
            
            #line default
            #line hidden
            this.Write("!=null&&condition.");
            
            #line 98 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Code));
            
            #line default
            #line hidden
            this.Write("s.Contains((int)q.");
            
            #line 98 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Code));
            
            #line default
            #line hidden
            this.Write("));\r\n");
            
            #line 99 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
}else{
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\tquery = query.Where(q => condition.");
            
            #line 100 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Code));
            
            #line default
            #line hidden
            this.Write("s.Contains(q.");
            
            #line 100 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Code));
            
            #line default
            #line hidden
            this.Write("));\r\n");
            
            #line 101 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
}}}
            
            #line default
            #line hidden
            this.Write("\t\t\t}\r\n\t\t\t#endregion\r\n\r\n\t\t\t#region 二级数据动态字段查询\r\n");
            
            #line 106 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
 foreach (var model in models.ColumnsList.Where(t => t.Virtual == false||(t.Virtual&&t.PK&&t.FK))){if(model.Virtual){
	var FCode=model.Code; var FkCode=model.Code.Split('_')[1];
   var FKEntity=_AllModels.Where(t=>t.Code==FkCode).FirstOrDefault();
if(FKEntity!=null){ 

            
            #line default
            #line hidden
            this.Write("\t\t\tvar ");
            
            #line 111 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FCode));
            
            #line default
            #line hidden
            this.Write("condition=condition.");
            
            #line 111 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Code));
            
            #line default
            #line hidden
            this.Write("Condition;\r\n\t\t\tif(");
            
            #line 112 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FCode));
            
            #line default
            #line hidden
            this.Write("condition!=null)\r\n\t\t\t{\r\n\t\t\t\t//query=query.Where(q=>q.");
            
            #line 114 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Code));
            
            #line default
            #line hidden
            this.Write("!=null);\r\n");
            
            #line 115 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
 foreach(var model2 in FKEntity.ColumnsList.Where(r=>r.Virtual==false).OrderByDescending(c => c.Search)){ 
var queryCode=model.Code+"."+model2.Code;
if(model2.Search == SearchType.Range){
            
            #line default
            #line hidden
            this.Write("\t\t\tif (");
            
            #line 118 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FCode));
            
            #line default
            #line hidden
            this.Write("condition.");
            
            #line 118 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model2.Code));
            
            #line default
            #line hidden
            this.Write("Begin.HasValue)\r\n\t\t\t{\r\n\t\t\t\t");
            
            #line 120 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
if(model2.CodeType.StartsWith("DateTime")){
            
            #line default
            #line hidden
            this.Write("\t\t\t\tvar ");
            
            #line 121 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model2.Code));
            
            #line default
            #line hidden
            this.Write("Begin=");
            
            #line 121 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FCode));
            
            #line default
            #line hidden
            this.Write("condition.");
            
            #line 121 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model2.Code));
            
            #line default
            #line hidden
            this.Write("Begin.Begin();\r\n                query = query.Where(q => q.");
            
            #line 122 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(queryCode));
            
            #line default
            #line hidden
            this.Write(" >= ");
            
            #line 122 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model2.Code));
            
            #line default
            #line hidden
            this.Write("Begin);\r\n\t\t\t\t");
            
            #line 123 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
}else{
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\tquery = query.Where(q => q.");
            
            #line 124 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(queryCode));
            
            #line default
            #line hidden
            this.Write(" >= ");
            
            #line 124 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FCode));
            
            #line default
            #line hidden
            this.Write("condition.");
            
            #line 124 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model2.Code));
            
            #line default
            #line hidden
            this.Write("Begin);\r\n\t\t\t\t");
            
            #line 125 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("\t\t\t}\r\n            if (");
            
            #line 127 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FCode));
            
            #line default
            #line hidden
            this.Write("condition.");
            
            #line 127 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model2.Code));
            
            #line default
            #line hidden
            this.Write("End.HasValue)\r\n\t\t\t{\r\n\t\t\t\t");
            
            #line 129 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
if(model2.CodeType.StartsWith("DateTime")){
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\tvar ");
            
            #line 130 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model2.Code));
            
            #line default
            #line hidden
            this.Write("End=");
            
            #line 130 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FCode));
            
            #line default
            #line hidden
            this.Write("condition.");
            
            #line 130 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model2.Code));
            
            #line default
            #line hidden
            this.Write("End.End();\r\n\t\t\t\t\tquery = query.Where(q => q.");
            
            #line 131 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(queryCode));
            
            #line default
            #line hidden
            this.Write(" <= ");
            
            #line 131 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model2.Code));
            
            #line default
            #line hidden
            this.Write("End);\r\n\t\t\t\t");
            
            #line 132 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
}else{
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\tquery = query.Where(q => q.");
            
            #line 133 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(queryCode));
            
            #line default
            #line hidden
            this.Write(" >= ");
            
            #line 133 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FCode));
            
            #line default
            #line hidden
            this.Write("condition.");
            
            #line 133 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model2.Code));
            
            #line default
            #line hidden
            this.Write("End);\r\n\t\t\t\t");
            
            #line 134 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("\t\t\t}\r\n");
            
            #line 136 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
 }else if(model2.Search == SearchType.Equal){
	if(model2.CodeType =="string"){
            
            #line default
            #line hidden
            this.Write("\t\t\tif (!string.IsNullOrEmpty(");
            
            #line 138 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FCode));
            
            #line default
            #line hidden
            this.Write("condition.");
            
            #line 138 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model2.Code));
            
            #line default
            #line hidden
            this.Write("))\r\n                query = query.Where(q => q.");
            
            #line 139 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(queryCode));
            
            #line default
            #line hidden
            this.Write(" == ");
            
            #line 139 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FCode));
            
            #line default
            #line hidden
            this.Write("condition.");
            
            #line 139 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model2.Code));
            
            #line default
            #line hidden
            this.Write(");\r\n\t");
            
            #line 140 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
} else if(model2.CodeType =="Guid"){
            
            #line default
            #line hidden
            this.Write("\t\t\tif (");
            
            #line 141 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FCode));
            
            #line default
            #line hidden
            this.Write("condition.");
            
            #line 141 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Code));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 141 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model2.Code));
            
            #line default
            #line hidden
            this.Write("!=Guid.Empty)\r\n                query = query.Where(q => q.");
            
            #line 142 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Code));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 142 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model2.Code));
            
            #line default
            #line hidden
            this.Write(" == ");
            
            #line 142 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FCode));
            
            #line default
            #line hidden
            this.Write("condition.");
            
            #line 142 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model2.Code));
            
            #line default
            #line hidden
            this.Write(");\r\n\t");
            
            #line 143 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
}else{
            
            #line default
            #line hidden
            this.Write("\t\t\tif (");
            
            #line 144 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FCode));
            
            #line default
            #line hidden
            this.Write("condition.");
            
            #line 144 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model2.Code));
            
            #line default
            #line hidden
            this.Write(".HasValue)\r\n                query = query.Where(q => ");
            
            #line 145 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((model2.EM==true?"(int)":"")));
            
            #line default
            #line hidden
            this.Write("q.");
            
            #line 145 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(queryCode));
            
            #line default
            #line hidden
            this.Write(" == ");
            
            #line 145 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FCode));
            
            #line default
            #line hidden
            this.Write("condition.");
            
            #line 145 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model2.Code));
            
            #line default
            #line hidden
            this.Write(".Value);\r\n\t");
            
            #line 146 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
 }
} else if(model2.Search == SearchType.Like){
		if(model2.CodeType =="string"){
            
            #line default
            #line hidden
            this.Write("\t\t\tif (!string.IsNullOrEmpty(");
            
            #line 149 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FCode));
            
            #line default
            #line hidden
            this.Write("condition.");
            
            #line 149 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model2.Code));
            
            #line default
            #line hidden
            this.Write("))\r\n                query = query.Where(q => q.");
            
            #line 150 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(queryCode));
            
            #line default
            #line hidden
            this.Write(".Contains(");
            
            #line 150 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FCode));
            
            #line default
            #line hidden
            this.Write("condition.");
            
            #line 150 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model2.Code));
            
            #line default
            #line hidden
            this.Write("));\r\n\t\t");
            
            #line 151 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
}else{
            
            #line default
            #line hidden
            this.Write("\t\t\tif (");
            
            #line 152 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FCode));
            
            #line default
            #line hidden
            this.Write("condition.");
            
            #line 152 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model2.Code));
            
            #line default
            #line hidden
            this.Write(".HasValue)\r\n                query = query.Where(q => q.");
            
            #line 153 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(queryCode));
            
            #line default
            #line hidden
            this.Write(".Contains(condition.");
            
            #line 153 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model2.Code));
            
            #line default
            #line hidden
            this.Write(".Value));\r\n");
            
            #line 154 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
}} else if(model2.Search == SearchType.In){
            
            #line default
            #line hidden
            this.Write("\t\t\tif (");
            
            #line 155 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FCode));
            
            #line default
            #line hidden
            this.Write("condition.");
            
            #line 155 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model2.Code));
            
            #line default
            #line hidden
            this.Write("s != null && ");
            
            #line 155 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FCode));
            
            #line default
            #line hidden
            this.Write("condition.");
            
            #line 155 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model2.Code));
            
            #line default
            #line hidden
            this.Write("s.Any())\r\n");
            
            #line 156 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
if(model2.IsNull){
            
            #line default
            #line hidden
            this.Write("                query = query.Where(q =>q.");
            
            #line 157 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(queryCode));
            
            #line default
            #line hidden
            this.Write("!=null&&");
            
            #line 157 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FCode));
            
            #line default
            #line hidden
            this.Write("condition.");
            
            #line 157 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model2.Code));
            
            #line default
            #line hidden
            this.Write("s.Contains((int)q.");
            
            #line 157 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(queryCode));
            
            #line default
            #line hidden
            this.Write("));\r\n");
            
            #line 158 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
}else{
            
            #line default
            #line hidden
            this.Write("\t\t\t\tquery = query.Where(q => ");
            
            #line 159 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FCode));
            
            #line default
            #line hidden
            this.Write("condition.");
            
            #line 159 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model2.Code));
            
            #line default
            #line hidden
            this.Write("s.Contains(q.");
            
            #line 159 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(queryCode));
            
            #line default
            #line hidden
            this.Write("));\r\n");
            
            #line 160 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
}}}
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 162 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t}\r\n");
            
            #line 165 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
}else{
            
            #line default
            #line hidden
            
            #line 166 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
if(model.FK&&!model.PK){var FCode=model.Code; var FkCode=model.FKTable.Replace("Entity", "");
var FKEntity=_AllModels.Where(t=>t.Code==FkCode).FirstOrDefault();if(FKEntity!=null){
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\r\n\t\t\t\t\tvar ");
            
            #line 169 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FCode));
            
            #line default
            #line hidden
            this.Write("condition=condition.");
            
            #line 169 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Code));
            
            #line default
            #line hidden
            this.Write("Condition;\r\n\t\t\t\t\tif(");
            
            #line 170 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FCode));
            
            #line default
            #line hidden
            this.Write("condition!=null)\r\n\t\t\t\t\t{\r\n\t\t\t\t\t\t//query=query.Where(q=>q.");
            
            #line 172 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Code+"_"+model.FKTable.Replace("Entity", "")));
            
            #line default
            #line hidden
            this.Write("!=null);\r\n");
            
            #line 173 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
 foreach(var model2 in FKEntity.ColumnsList.Where(r=>r.Virtual==false).OrderByDescending(c => c.Search)){ 
var queryCode=model.Code+"_"+model.FKTable.Replace("Entity", "")+"."+model2.Code;
if(model2.Search == SearchType.Range){
            
            #line default
            #line hidden
            this.Write("\t\t\tif (");
            
            #line 176 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FCode));
            
            #line default
            #line hidden
            this.Write("condition.");
            
            #line 176 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model2.Code));
            
            #line default
            #line hidden
            this.Write("Begin.HasValue)\r\n\t\t\t{\r\n\t\t\t\t");
            
            #line 178 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
if(model2.CodeType.StartsWith("DateTime")){
            
            #line default
            #line hidden
            this.Write("\t\t\t\tvar ");
            
            #line 179 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model2.Code));
            
            #line default
            #line hidden
            this.Write("Begin=");
            
            #line 179 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FCode));
            
            #line default
            #line hidden
            this.Write("condition.");
            
            #line 179 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model2.Code));
            
            #line default
            #line hidden
            this.Write("Begin.Begin();\r\n                query = query.Where(q => q.");
            
            #line 180 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(queryCode));
            
            #line default
            #line hidden
            this.Write(" >= ");
            
            #line 180 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model2.Code));
            
            #line default
            #line hidden
            this.Write("Begin);\r\n\t\t\t\t");
            
            #line 181 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
}else{
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\tquery = query.Where(q => q.");
            
            #line 182 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(queryCode));
            
            #line default
            #line hidden
            this.Write(" >= ");
            
            #line 182 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FCode));
            
            #line default
            #line hidden
            this.Write("condition.");
            
            #line 182 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model2.Code));
            
            #line default
            #line hidden
            this.Write("Begin);\r\n\t\t\t\t");
            
            #line 183 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("\t\t\t}\r\n            if (");
            
            #line 185 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FCode));
            
            #line default
            #line hidden
            this.Write("condition.");
            
            #line 185 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model2.Code));
            
            #line default
            #line hidden
            this.Write("End.HasValue)\r\n\t\t\t{\r\n\t\t\t\t");
            
            #line 187 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
if(model2.CodeType.StartsWith("DateTime")){
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\tvar ");
            
            #line 188 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model2.Code));
            
            #line default
            #line hidden
            this.Write("End=");
            
            #line 188 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FCode));
            
            #line default
            #line hidden
            this.Write("condition.");
            
            #line 188 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model2.Code));
            
            #line default
            #line hidden
            this.Write("End.End();\r\n\t\t\t\t\tquery = query.Where(q => q.");
            
            #line 189 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(queryCode));
            
            #line default
            #line hidden
            this.Write(" <= ");
            
            #line 189 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model2.Code));
            
            #line default
            #line hidden
            this.Write("End);\r\n\t\t\t\t");
            
            #line 190 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
}else{
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\tquery = query.Where(q => q.");
            
            #line 191 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(queryCode));
            
            #line default
            #line hidden
            this.Write(" >= ");
            
            #line 191 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FCode));
            
            #line default
            #line hidden
            this.Write("condition.");
            
            #line 191 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model2.Code));
            
            #line default
            #line hidden
            this.Write("End);\r\n\t\t\t\t");
            
            #line 192 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("\t\t\t}\r\n");
            
            #line 194 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
 }else if(model2.Search == SearchType.Equal){
	if(model2.CodeType =="string"){
            
            #line default
            #line hidden
            this.Write("\t\t\tif (!string.IsNullOrEmpty(");
            
            #line 196 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FCode));
            
            #line default
            #line hidden
            this.Write("condition.");
            
            #line 196 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model2.Code));
            
            #line default
            #line hidden
            this.Write("))\r\n                query = query.Where(q => q.");
            
            #line 197 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(queryCode));
            
            #line default
            #line hidden
            this.Write(" == ");
            
            #line 197 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FCode));
            
            #line default
            #line hidden
            this.Write("condition.");
            
            #line 197 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model2.Code));
            
            #line default
            #line hidden
            this.Write(");\r\n\t");
            
            #line 198 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
} else if(model2.CodeType =="Guid"){
            
            #line default
            #line hidden
            this.Write("\t\t\tif (");
            
            #line 199 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FCode));
            
            #line default
            #line hidden
            this.Write("condition.");
            
            #line 199 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Code));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 199 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model2.Code));
            
            #line default
            #line hidden
            this.Write("!=Guid.Empty)\r\n                query = query.Where(q => q.");
            
            #line 200 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Code));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 200 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model2.Code));
            
            #line default
            #line hidden
            this.Write(" == ");
            
            #line 200 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FCode));
            
            #line default
            #line hidden
            this.Write("condition.");
            
            #line 200 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model2.Code));
            
            #line default
            #line hidden
            this.Write(");\r\n\t");
            
            #line 201 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
}else{
            
            #line default
            #line hidden
            this.Write("\t\t\tif (");
            
            #line 202 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FCode));
            
            #line default
            #line hidden
            this.Write("condition.");
            
            #line 202 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model2.Code));
            
            #line default
            #line hidden
            this.Write(".HasValue)\r\n                query = query.Where(q => ");
            
            #line 203 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((model2.EM==true?"(int)":"")));
            
            #line default
            #line hidden
            this.Write("q.");
            
            #line 203 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(queryCode));
            
            #line default
            #line hidden
            this.Write(" == ");
            
            #line 203 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FCode));
            
            #line default
            #line hidden
            this.Write("condition.");
            
            #line 203 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model2.Code));
            
            #line default
            #line hidden
            this.Write(".Value);\r\n\t");
            
            #line 204 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
 }
} else if(model2.Search == SearchType.Like){
		if(model2.CodeType =="string"){
            
            #line default
            #line hidden
            this.Write("\t\t\tif (!string.IsNullOrEmpty(");
            
            #line 207 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FCode));
            
            #line default
            #line hidden
            this.Write("condition.");
            
            #line 207 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model2.Code));
            
            #line default
            #line hidden
            this.Write("))\r\n                query = query.Where(q => q.");
            
            #line 208 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(queryCode));
            
            #line default
            #line hidden
            this.Write(".Contains(");
            
            #line 208 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FCode));
            
            #line default
            #line hidden
            this.Write("condition.");
            
            #line 208 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model2.Code));
            
            #line default
            #line hidden
            this.Write("));\r\n\t\t");
            
            #line 209 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
}else{
            
            #line default
            #line hidden
            this.Write("\t\t\tif (");
            
            #line 210 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FCode));
            
            #line default
            #line hidden
            this.Write("condition.");
            
            #line 210 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model2.Code));
            
            #line default
            #line hidden
            this.Write(".HasValue)\r\n                query = query.Where(q => q.");
            
            #line 211 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(queryCode));
            
            #line default
            #line hidden
            this.Write(".Contains(condition.");
            
            #line 211 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model2.Code));
            
            #line default
            #line hidden
            this.Write(".Value));\r\n");
            
            #line 212 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
}} else if(model2.Search == SearchType.In){
            
            #line default
            #line hidden
            this.Write("\t\t\tif (");
            
            #line 213 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FCode));
            
            #line default
            #line hidden
            this.Write("condition.");
            
            #line 213 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model2.Code));
            
            #line default
            #line hidden
            this.Write("s != null && ");
            
            #line 213 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FCode));
            
            #line default
            #line hidden
            this.Write("condition.");
            
            #line 213 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model2.Code));
            
            #line default
            #line hidden
            this.Write("s.Any())\r\n");
            
            #line 214 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
if(model2.IsNull){
            
            #line default
            #line hidden
            this.Write("                query = query.Where(q =>q.");
            
            #line 215 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(queryCode));
            
            #line default
            #line hidden
            this.Write("!=null&&");
            
            #line 215 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FCode));
            
            #line default
            #line hidden
            this.Write("condition.");
            
            #line 215 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model2.Code));
            
            #line default
            #line hidden
            this.Write("s.Contains((int)q.");
            
            #line 215 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(queryCode));
            
            #line default
            #line hidden
            this.Write("));\r\n");
            
            #line 216 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
}else{
            
            #line default
            #line hidden
            this.Write("\t\t\t\tquery = query.Where(q => ");
            
            #line 217 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FCode));
            
            #line default
            #line hidden
            this.Write("condition.");
            
            #line 217 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model2.Code));
            
            #line default
            #line hidden
            this.Write("s.Contains(q.");
            
            #line 217 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(queryCode));
            
            #line default
            #line hidden
            this.Write("));\r\n");
            
            #line 218 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
}}}
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t}\r\n");
            
            #line 220 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_DotnetCore\CoreBaseServiceTemplate.tt"
}}}}
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t#endregion\r\n\r\n\t\t\treturn query;\r\n\t\t}\r\n\t}\r\n}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public class CoreBaseServiceTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
