// ------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本: 16.0.0.0
//  
//     对此文件的更改可能导致不正确的行为，如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace FileLoder.T_LigerUI
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_LigerUI\EditTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class EditTemplate : EditTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("@{\r\n    ViewBag.Title = \"AdminHome\";\r\n    Layout = \"~/Areas/Admin/Views/Shared/_l" +
                    "ayout.cshtml\";\r\n}\r\n");
            
            #line 10 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_LigerUI\EditTemplate.tt"
 var PKData=models.ColumnsList.Where(t =>t.PK==true).FirstOrDefault();
	if(PKData==null) throw new Exception("未包含主键字段");

            
            #line default
            #line hidden
            this.Write(@"<style type=""text/css"">
    body {
        padding-left: 10px;
        font-size: 13px;
    }

    h1 {
        font-size: 20px;
        font-family: Verdana;
    }

    h4 {
        font-size: 16px;
        margin-top: 25px;
        margin-bottom: 10px;
    }

    .description {
        padding-bottom: 30px;
        font-family: Verdana;
    }

        .description h3 {
            color: #CC0000;
            font-size: 16px;
            margin: 0 30px 10px 0px;
            padding: 45px 0 8px;
            border-bottom: solid 1px #888;
        }

    td {
        padding: 5px;
    }
</style>

<script type=""text/javascript"">
    $(document).ready(function () {
        $(""#");
            
            #line 50 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_LigerUI\EditTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityName));
            
            #line default
            #line hidden
            this.Write("\").ligerForm({\r\n            validate: true\r\n        });\r\n\t\tvar ");
            
            #line 53 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_LigerUI\EditTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PKData.Code));
            
            #line default
            #line hidden
            this.Write("=getQueryString(\"");
            
            #line 53 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_LigerUI\EditTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PKData.Code));
            
            #line default
            #line hidden
            this.Write("\");\r\n\t\tif(");
            
            #line 54 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_LigerUI\EditTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PKData.Code));
            
            #line default
            #line hidden
            this.Write("!=null){\r\n\t\t\t$(document).attr(\"title\",\"修改\");\r\n\t\t\tcommon.Ajax({\r\n\t\t\t\tshowLoading: " +
                    "false,\r\n\t\t\t\tshowMsg: false,\r\n                url: \"/Api/");
            
            #line 59 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_LigerUI\EditTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(models.Code));
            
            #line default
            #line hidden
            this.Write("/GetById\",\r\n                data: {\"\":");
            
            #line 60 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_LigerUI\EditTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PKData.Code));
            
            #line default
            #line hidden
            this.Write("},\r\n                afterAjaxSuccessHandler: function (data) {\r\n                 " +
                    "   var form = new liger.get(\"");
            
            #line 62 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_LigerUI\EditTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityName));
            
            #line default
            #line hidden
            this.Write("\");\r\n\t\t\t\t\tform.setData(data);\r\n\r\n");
            
            #line 65 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_LigerUI\EditTemplate.tt"
 foreach(var pmodel in models.ColumnsList.Where(t=>t.Virtual==false)){ if(pmodel.FK){
		var item=_AllModel.Where(t=>t.Code==pmodel.FKTable.Replace("Entity", "")).FirstOrDefault();
		var pk=item.ColumnsList.Where(t=>t.PK==true).FirstOrDefault();
		var model3=item.ColumnsList.Where(t=>t.Virtual==false&&t.CodeType=="string").FirstOrDefault();
		var code3=pk.Code;var comment=pk.Name;
		if(model3!=null){
			code3=model3.Code.Replace("?","");
			comment=model3.Name;
		}
		var Code3=model3==null? pk.Code:model3.Code.Replace("?","");

            
            #line default
            #line hidden
            this.Write("\t\t\t\t\tif(data.");
            
            #line 76 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_LigerUI\EditTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pmodel.Code));
            
            #line default
            #line hidden
            this.Write("!=null){\r\n\t\t\t\t\t\tcommon.Ajax({\r\n\t\t\t\t\t\t\tshowLoading: false,\r\n\t\t\t\t\t\t\tshowMsg: false," +
                    "\r\n\t\t\t\t\t\t\turl: \"/Api/");
            
            #line 80 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_LigerUI\EditTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code));
            
            #line default
            #line hidden
            this.Write("/GetById\",\r\n\t\t\t\t\t\t\tdata: {\"\":data.");
            
            #line 81 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_LigerUI\EditTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pmodel.Code));
            
            #line default
            #line hidden
            this.Write("},\r\n\t\t\t\t\t\t\tafterAjaxSuccessHandler: function (data) {\r\n\t\t\t\t\t\t\t$(\"#");
            
            #line 83 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_LigerUI\EditTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pmodel.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("Text\").val(data.");
            
            #line 83 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_LigerUI\EditTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(code3));
            
            #line default
            #line hidden
            this.Write(");\r\n\t\t\t\t\t\t\t}\r\n\t\t\t\t\t\t});\r\n\t\t\t\t\t}\r\n");
            
            #line 87 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_LigerUI\EditTemplate.tt"
}}
            
            #line default
            #line hidden
            this.Write("                }\r\n            });\r\n\t\t}\r\n\t\telse{\r\n\t\t\t$(document).attr(\"title\",\"新增" +
                    "\");\r\n\t\t}\r\n\r\n");
            
            #line 95 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_LigerUI\EditTemplate.tt"
 foreach(var pmodel in models.ColumnsList.Where(t=>t.Virtual==false)){ if(pmodel.FK){
		var item=_AllModel.Where(t=>t.Code==pmodel.FKTable.Replace("Entity", "")).FirstOrDefault();
		var pk=item.ColumnsList.Where(t=>t.PK==true).FirstOrDefault();
		var model3=item.ColumnsList.Where(t=>t.Virtual==false&&t.CodeType=="string").FirstOrDefault();
		var code3=pk.Code;var comment=pk.Name;
		if(model3!=null){
			code3=model3.Code.Replace("?","");
			comment=model3.Name;
		}
		var Code3=model3==null? pk.Code:model3.Code.Replace("?","");

            
            #line default
            #line hidden
            this.Write("\t\r\n\t$(\"#");
            
            #line 107 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_LigerUI\EditTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pmodel.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("Text\").ligerComboBox({\r\n            condition: { fields: [{ ");
            
            #line 108 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_LigerUI\EditTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(code3));
            
            #line default
            #line hidden
            this.Write(": \'");
            
            #line 108 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_LigerUI\EditTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(code3));
            
            #line default
            #line hidden
            this.Write("\', label: \'");
            
            #line 108 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_LigerUI\EditTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(comment));
            
            #line default
            #line hidden
            this.Write("\', width: 120 }] },//搜索框的字段, name 必须是服务器返回的字段  \r\n            grid: get");
            
            #line 109 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_LigerUI\EditTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code));
            
            #line default
            #line hidden
            this.Write("Options(false),\r\n            valueFieldID: \'");
            
            #line 110 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_LigerUI\EditTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pmodel.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("\',\r\n            valueField: \'");
            
            #line 111 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_LigerUI\EditTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pk.Code));
            
            #line default
            #line hidden
            this.Write("\',//请求参数key  \r\n            textField: \'");
            
            #line 112 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_LigerUI\EditTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Code3));
            
            #line default
            #line hidden
            this.Write("\',//搜索框输入的值  \r\n            width: 310,\r\n            selectBoxHeight: 216,\r\n      " +
                    "      slide: false, //淡入淡出  \r\n            onSelected: function (id, name) {//id为" +
                    "空值，name为选择的值  \r\n                //$(\"#");
            
            #line 117 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_LigerUI\EditTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pmodel.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("\").val(name);//下拉框选择后文本框的值  \r\n            }\r\n        });\r\n        function get");
            
            #line 120 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_LigerUI\EditTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code));
            
            #line default
            #line hidden
            this.Write("Options(checkbox) {\r\n            var  ");
            
            #line 121 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_LigerUI\EditTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code));
            
            #line default
            #line hidden
            this.Write("=\r\n\t\t\t{\r\n                columns: [\r\n");
            
            #line 124 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_LigerUI\EditTemplate.tt"
var data=item.ColumnsList.Where(t=>t.Virtual==false&&t.PK!=true).ToList();
	int p=1,Count=data.Count();
	foreach(var model in data){
            
            #line default
            #line hidden
            
            #line 127 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_LigerUI\EditTemplate.tt"
 if(model.EM){
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t{ display: \'");
            
            #line 128 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_LigerUI\EditTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Name));
            
            #line default
            #line hidden
            this.Write("\', name: \'");
            
            #line 128 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_LigerUI\EditTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Code+"String"));
            
            #line default
            #line hidden
            this.Write("\', width: 100 }");
            
            #line 128 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_LigerUI\EditTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(p==Count?"":","));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 129 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_LigerUI\EditTemplate.tt"
}else { var render="";if(model.DataType=="bit") render=", render: readerStatus";else if(model.DataType=="datetime") render=", render: ChangeDateFormat2"; 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t{ display: \'");
            
            #line 130 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_LigerUI\EditTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Name));
            
            #line default
            #line hidden
            this.Write("\', name: \'");
            
            #line 130 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_LigerUI\EditTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Code));
            
            #line default
            #line hidden
            this.Write("\', width: 100 ");
            
            #line 130 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_LigerUI\EditTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(render));
            
            #line default
            #line hidden
            this.Write(" }");
            
            #line 130 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_LigerUI\EditTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(p==Count?"":","));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 131 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_LigerUI\EditTemplate.tt"
}p++;}
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t],\r\n                switchPageSizeApplyComboBox: false,\r\n                //请" +
                    "求地址  \r\n                url: \"/Api/");
            
            #line 135 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_LigerUI\EditTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code));
            
            #line default
            #line hidden
            this.Write("/GetListData\",\r\n                root: \"Records\",\r\n\t\t\t\trecord: \"TotalCount\",\r\n\t\t\t\t" +
                    "pagesizeParmName: \"PageCount\",\r\n\t\t\t\tpageParmName: \"Page\",\r\n\t\t\t\tdateFormat: \"\",\r\n" +
                    "\t\t\t\tcheckbox: checkbox,\r\n\t\t\t\tfrozen:true  \r\n            };\r\n\t\t\treturn ");
            
            #line 144 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_LigerUI\EditTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code));
            
            #line default
            #line hidden
            this.Write(";\r\n        }\r\n");
            
            #line 146 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_LigerUI\EditTemplate.tt"
}}
            
            #line default
            #line hidden
            this.Write("    });\r\n\tfunction Save(currentDialog, saveSuccess) {\r\n        var form = new lig" +
                    "er.get(\"");
            
            #line 149 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_LigerUI\EditTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityName));
            
            #line default
            #line hidden
            this.Write("\");\r\n        if (form.valid()) {\r\n            common.Ajax({\r\n                url:" +
                    " \"/Api/");
            
            #line 152 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_LigerUI\EditTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(models.Code));
            
            #line default
            #line hidden
            this.Write("/CreateOrModify\",\r\n                data: $(\"#");
            
            #line 153 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_LigerUI\EditTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityName));
            
            #line default
            #line hidden
            this.Write("\").serialize(),\r\n                afterAjaxSuccessHandler: function (data) {\r\n    " +
                    "                saveSuccess(data);\r\n                    currentDialog.close();\r\n" +
                    "                }\r\n            });\r\n        }\r\n    }\r\n</script>\r\n<form id=\"");
            
            #line 162 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_LigerUI\EditTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityName));
            
            #line default
            #line hidden
            this.Write("\" class=\"ui-form\">\r\n    <table>\r\n");
            
            #line 164 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_LigerUI\EditTemplate.tt"
foreach(var item in models.ColumnsList.Where(t=>t.Virtual==false)){
	var Code=_entityName+item.Code;
	if(item.CodeType=="bool"){
            
            #line default
            #line hidden
            this.Write("\t\t<tr>\r\n            <td>\r\n                ");
            
            #line 169 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_LigerUI\EditTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name==null?item.Comment==null?"":item.Comment:item.Name));
            
            #line default
            #line hidden
            this.Write("：\r\n            </td>\r\n            <td>\r\n                <input name=\"");
            
            #line 172 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_LigerUI\EditTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("\" class=\"ui-checkbox\" type=\"text\" text=\"");
            
            #line 172 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_LigerUI\EditTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name==null?item.Comment==null?"":item.Comment:item.Name));
            
            #line default
            #line hidden
            this.Write("\" validate=\"{required:");
            
            #line 172 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_LigerUI\EditTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.IsNull?"false":"true"));
            
            #line default
            #line hidden
            this.Write("}\" />\r\n            </td>\r\n        </tr>\r\n");
            
            #line 175 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_LigerUI\EditTemplate.tt"
}else if(item.EM){
            
            #line default
            #line hidden
            this.Write("\t\t<tr>\r\n            <td>\r\n                ");
            
            #line 178 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_LigerUI\EditTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name==null?item.Comment==null?"":item.Comment:item.Name));
            
            #line default
            #line hidden
            this.Write("：\r\n            </td>\r\n            <td>\r\n                <select name=\"");
            
            #line 181 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_LigerUI\EditTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("\" validate=\"{required:");
            
            #line 181 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_LigerUI\EditTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.IsNull?"false":"true"));
            
            #line default
            #line hidden
            this.Write("}\">\r\n\t\t\t\t\t<option value=\"\" selected=\"selected\" >请选择...</option>\r\n");
            
            #line 183 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_LigerUI\EditTemplate.tt"
foreach(var em in item.EmodelList){
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t<option value=\"");
            
            #line 184 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_LigerUI\EditTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(em.Attribute));
            
            #line default
            #line hidden
            this.Write("\" >");
            
            #line 184 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_LigerUI\EditTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(em.Description));
            
            #line default
            #line hidden
            this.Write("</option>\r\n");
            
            #line 185 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_LigerUI\EditTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("                </select>\r\n            </td>\r\n        </tr>\r\n");
            
            #line 189 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_LigerUI\EditTemplate.tt"
}else if(item.FK){
            
            #line default
            #line hidden
            this.Write("\t\t<tr>\r\n            <td>\r\n                ");
            
            #line 192 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_LigerUI\EditTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name==null?item.Comment==null?"":item.Comment:item.Name));
            
            #line default
            #line hidden
            this.Write("：\r\n            </td>\r\n            <td>\r\n                <input id=\"");
            
            #line 195 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_LigerUI\EditTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("Text\" name=\"");
            
            #line 195 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_LigerUI\EditTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("Text\" validate=\"{required:");
            
            #line 195 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_LigerUI\EditTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.IsNull?"false":"true"));
            
            #line default
            #line hidden
            this.Write("}\" />\r\n            </td>\r\n        </tr>\r\n");
            
            #line 198 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_LigerUI\EditTemplate.tt"
}else if(item.PK) {
            
            #line default
            #line hidden
            this.Write("\t\t<input id=\"");
            
            #line 199 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_LigerUI\EditTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("\" type=\"hidden\" name=\"");
            
            #line 199 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_LigerUI\EditTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("\" validate=\"{required:false}\" />\r\n");
            
            #line 200 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_LigerUI\EditTemplate.tt"
}else {
            
            #line default
            #line hidden
            this.Write("\t\t<tr>\r\n            <td>\r\n                <label for=\"textbox1\">");
            
            #line 203 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_LigerUI\EditTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name==null?item.Comment==null?"":item.Comment:item.Name));
            
            #line default
            #line hidden
            this.Write("：</label>\r\n            </td>\r\n            <td>\r\n\t\t\t");
            
            #line 206 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_LigerUI\EditTemplate.tt"

				var require=item.IsNull?"false":"true";
			
            
            #line default
            #line hidden
            this.Write("                <input  id=\"");
            
            #line 209 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_LigerUI\EditTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("\" name=\"");
            
            #line 209 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_LigerUI\EditTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("\" type=\"text\" class=\"");
            
            #line 209 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_LigerUI\EditTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.CodeType=="DateTime"?"ui-datepicker":"ui-textbox"));
            
            #line default
            #line hidden
            this.Write("\" validate=\"{required:");
            
            #line 209 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_LigerUI\EditTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(require));
            
            #line default
            #line hidden
            this.Write("}\" />\r\n            </td>\r\n        </tr>\r\n");
            
            #line 212 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_LigerUI\EditTemplate.tt"
}}
            
            #line default
            #line hidden
            this.Write("    </table>\r\n</form>\r\n\r\n\r\n\r\n    \r\n\t\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public class EditTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
