// ------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本: 16.0.0.0
//  
//     对此文件的更改可能导致不正确的行为，如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace FileLoder.T_Android
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class J_DataViewMainEventTemplate : J_DataViewMainEventTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("\r\npackage ");
            
            #line 7 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_package));
            
            #line default
            #line hidden
            this.Write(".Event;\r\nimport android.app.Activity;\r\nimport android.content.Context;\r\nimport an" +
                    "droid.database.Cursor;\r\nimport java.util.ArrayList;\r\nimport java.util.Arrays;\r\ni" +
                    "mport java.util.List;\r\nimport android.databinding.DataBindingUtil;\r\nimport ");
            
            #line 15 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_package));
            
            #line default
            #line hidden
            this.Write(".Dialog.ListViewDialog;\r\nimport ");
            
            #line 16 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_package));
            
            #line default
            #line hidden
            this.Write(".Dialog.MyDialog;\r\nimport ");
            
            #line 17 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_package));
            
            #line default
            #line hidden
            this.Write(@".Common.Util;
import android.os.Bundle;
import android.os.StrictMode;
import android.support.v4.app.Fragment;
import android.support.v4.widget.SimpleCursorAdapter;
import android.support.v4.widget.SwipeRefreshLayout;
import android.support.v7.widget.RecyclerView;
import android.support.v7.widget.LinearLayoutManager;
import android.support.v7.widget.StaggeredGridLayoutManager;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ArrayAdapter;
import android.widget.ListView;
import ");
            
            #line 31 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_package));
            
            #line default
            #line hidden
            this.Write(".Common.LoadUtil;\r\nimport ");
            
            #line 32 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_package));
            
            #line default
            #line hidden
            this.Write(".ViewModel.*;\r\nimport ");
            
            #line 33 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_package));
            
            #line default
            #line hidden
            this.Write(".Fragment.*;\r\nimport ");
            
            #line 34 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_package));
            
            #line default
            #line hidden
            this.Write(".Model.*;\r\nimport ");
            
            #line 35 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_package));
            
            #line default
            #line hidden
            this.Write(".Service.*;\r\nimport ");
            
            #line 36 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_package));
            
            #line default
            #line hidden
            this.Write(".Data.*;\r\nimport ");
            
            #line 37 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_package));
            
            #line default
            #line hidden
            this.Write(".Base.*;\r\nimport ");
            
            #line 38 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_package));
            
            #line default
            #line hidden
            this.Write(".Adapter.*;\r\nimport ");
            
            #line 39 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_package));
            
            #line default
            #line hidden
            this.Write(".Event.*;\r\nimport ");
            
            #line 40 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_package));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 40 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_projectName));
            
            #line default
            #line hidden
            this.Write(".R;\r\nimport ");
            
            #line 41 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_package));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 41 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_projectName));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 41 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_projectName));
            
            #line default
            #line hidden
            this.Write(".DataLayoutBinding;\r\nimport ");
            
            #line 42 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_package));
            
            #line default
            #line hidden
            this.Write(".Common.ToastUtil;\r\nimport rx.Subscriber;\r\nimport android.widget.AdapterView;\r\nim" +
                    "port rx.subscriptions.CompositeSubscription;\r\nimport android.support.v4.app.Frag" +
                    "mentTransaction;\r\nimport android.support.v4.app.FragmentManager;\r\nimport com.goo" +
                    "gle.gson.Gson;\r\nimport com.google.gson.reflect.TypeToken;\r\nimport java.lang.refl" +
                    "ect.Type;\r\n\r\npublic class DataViewEvent{\r\n\r\n\tprivate LoadUtil _loading;\r\n\tprivat" +
                    "e CompositeSubscription _subscriptions;\r\n\tprivate DataLayoutBinding _binding;\r\n " +
                    "   private Bundle _bundle;\r\n\tprivate FragmentManager _manage;\r\n    private ListV" +
                    "iewDialog _ListViewDialog;\r\n\tprivate RecyclerView.LayoutManager _LayoutManager;\r" +
                    "\n    private MyDialog _mydialog;\r\n    private ActionService _actionService;\r\n\tpr" +
                    "ivate Activity _activity;\r\n\tprivate int Page=1,PageCount=20,OrderBy=0,TotalPage=" +
                    "0,TotalCount=0;\r\n\tprivate boolean IsDescending=true,isLoading=false;\r\n\tprivate i" +
                    "nt ClickID;\r\n\tprivate Context _context;\r\n\r\n\tpublic DataViewEvent(DataLayoutBindi" +
                    "ng binding,Context context,CompositeSubscription subscriptions,LoadUtil loading," +
                    "Activity activity,FragmentManager manage,Bundle bundle) {\r\n        this._binding" +
                    "=binding;\r\n\t\tthis._context=context;\r\n\t\tthis._subscriptions=subscriptions;\r\n\t\tthi" +
                    "s._loading=loading;\r\n\t\tthis._activity=activity;\r\n\t\tthis._manage=manage;\r\n\t\tthis." +
                    "_bundle=bundle;\r\n\t\tthis._mydialog=new MyDialog(_context,new MyDialogViewModel(\"提" +
                    "示\",\"确定要删除么?\",\"确定\",\"取消\"),deletelistener);\r\n        this._ListViewDialog=new ListV" +
                    "iewDialog(_context);\r\n        this._actionService = new ActionService(_context, " +
                    "_loading);\r\n\t\tthis._LayoutManager=new StaggeredGridLayoutManager(2, StaggeredGri" +
                    "dLayoutManager.VERTICAL);\r\n\t\tthis.ClickID=_bundle.getInt(\"ID\");\r\n\t\tInit();\r\n    " +
                    "}\r\n\r\n\tpublic String GetDataString(){\r\n\t\tGson gson = new Gson();\r\n\t\tString Data=\"" +
                    "\";\r\n\t\tswitch (ClickID) {\r\n");
            
            #line 89 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
foreach(var item in _models){
            
            #line default
            #line hidden
            
            #line 90 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
 var PKData=item.ColumnsList.Where(t=>t.PK==true).FirstOrDefault();
	if(PKData==null) throw new Exception("未包含主键字段");

            
            #line default
            #line hidden
            this.Write("\t\t\tcase R.id.");
            
            #line 93 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("_List:\r\n\t\t\t\tPageList<");
            
            #line 94 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("Model> ");
            
            #line 94 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("Data=new PageList<");
            
            #line 94 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("Model>();\r\n\t\t\t\tRecycle");
            
            #line 95 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("Adapter ");
            
            #line 95 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("Adapter = (Recycle");
            
            #line 95 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("Adapter)_binding.DataView.getAdapter();\r\n\t\t\t\tList<");
            
            #line 96 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("ViewModel> ");
            
            #line 96 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("=");
            
            #line 96 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("Adapter.getData();\r\n\t\t\t\tList<");
            
            #line 97 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("Model> ");
            
            #line 97 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("Model=new ArrayList<>();\r\n\t\t\t\tif(");
            
            #line 98 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("!=null&&");
            
            #line 98 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write(".size()>0){\r\n\t\t\t\t\tfor (");
            
            #line 99 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("ViewModel item : ");
            
            #line 99 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write(") {\r\n                            ");
            
            #line 100 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("Model.add(item.getModel());\r\n                    }\r\n\t\t\t\t}\r\n\t\t\t\t");
            
            #line 103 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("Data.TotalCount=TotalCount;\r\n\t\t\t\t");
            
            #line 104 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("Data.Records= ");
            
            #line 104 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("Model;\r\n\t\t\t\t");
            
            #line 105 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("Data.TotalPage=TotalPage;\r\n\t\t\t\t");
            
            #line 106 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("Data.Page=Page;\r\n\t\t\t\t");
            
            #line 107 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("Data.PageCount=PageCount;\r\n\t\t\t\tData=gson.toJson(");
            
            #line 108 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("Data);\r\n\t\t\t\tbreak;\r\n");
            
            #line 110 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write(@"		} 
		return Data;
	}

	private void Init()
	{
		_binding.DataAdd.setOnClickListener(listener);
		_binding.DataRefresh.setOnRefreshListener(RefreshListener);
		_binding.DataRefresh.setColorSchemeResources(android.R.color.holo_blue_bright, android.R.color.holo_green_light,
			android.R.color.holo_orange_light, android.R.color.holo_red_light);
		_binding.DataView.setLayoutManager(_LayoutManager);
		_binding.DataView.addOnScrollListener(liser);
		
		String data = _bundle.getString(""_DataViewModel"", """");
		Gson gson = new Gson();
		switch (ClickID)
		{
");
            
            #line 128 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
foreach(var item in _models){
            
            #line default
            #line hidden
            
            #line 129 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
 var PKData=item.ColumnsList.Where(t=>t.PK==true).FirstOrDefault();
	if(PKData==null) throw new Exception("未包含主键字段");

            
            #line default
            #line hidden
            this.Write("            case R.id.");
            
            #line 132 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("_List:\r\n");
            
            #line 133 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
 if(item.Code=="Action") {
            
            #line default
            #line hidden
            this.Write("\t\t\t_binding.DataAdd.setImageResource(android.R.drawable.ic_menu_preferences);\r\n");
            
            #line 135 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
 }
            
            #line default
            #line hidden
            this.Write("\t\t\t_activity.setTitle(\"");
            
            #line 136 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\");\r\n\t\t\tif (!Util.IsNullOrEmpty(data)) \r\n\t\t\t{\t\r\n\t\t\t\tType type = new TypeToken<Pag" +
                    "eList<");
            
            #line 139 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("Model>>() {\r\n\t\t\t\t}.getType();\r\n\t\t\t\tPageList<");
            
            #line 141 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("Model> ");
            
            #line 141 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("Model = gson.fromJson(data, type);\r\n\r\n\t\t\t\tList<");
            
            #line 143 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("ViewModel> ");
            
            #line 143 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write(" = new ArrayList<>();\r\n                for (");
            
            #line 144 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("Model item : ");
            
            #line 144 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("Model.Records) {\r\n                    ");
            
            #line 145 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write(".add(item.get");
            
            #line 145 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("ViewModel());\r\n                }\r\n\t\t\t\tTotalCount=");
            
            #line 147 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("Model.TotalCount;\r\n\t\t\t\tTotalPage=");
            
            #line 148 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("Model.TotalPage;\r\n\t\t\t\tPage=");
            
            #line 149 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("Model.Page;\r\n\t\t\t\tPageCount=");
            
            #line 150 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("Model.PageCount;\r\n\t\t\t\tfinal Recycle");
            
            #line 151 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("Adapter ");
            
            #line 151 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("Adapter = new Recycle");
            
            #line 151 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("Adapter(");
            
            #line 151 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write(");\r\n                _binding.DataView.setAdapter(");
            
            #line 152 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("Adapter);\r\n\t\t\t\t");
            
            #line 153 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("Adapter.setOnItemActionListener(new Recycle");
            
            #line 153 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("Adapter.OnItemActionListener() {\r\n\t\t\t\t\t\t@Override\r\n\t\t\t\t\t\tpublic boolean onItemLon" +
                    "gClickListener(View v, int pos) {\r\n\t\t\t\t\t\t\tBundle myDialogBundle=new Bundle();\r\n\t" +
                    "\t\t\t\t\t\tmyDialogBundle.putInt(\"position\",pos);\r\n\t\t\t\t\t\t\t");
            
            #line 158 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("ViewModel  ");
            
            #line 158 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("=");
            
            #line 158 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("Adapter.getItem(pos);\r\n\t\t\t\t\t\t\tmyDialogBundle.put");
            
            #line 159 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PKData.CodeType.Substring(0, 1).ToUpper() +PKData.CodeType.Substring(1).ToLower()));
            
            #line default
            #line hidden
            this.Write("(\"");
            
            #line 159 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PKData.Code));
            
            #line default
            #line hidden
            this.Write("\",");
            
            #line 159 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write(".get");
            
            #line 159 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            
            #line 159 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PKData.Code));
            
            #line default
            #line hidden
            this.Write("());\r\n\t\t\t\t\t\t\t_mydialog.setBundle(myDialogBundle);\r\n\t\t\t\t\t\t\t_mydialog.Show();\r\n\t\t\t\t" +
                    "\t\t\treturn true;\r\n\t\t\t\t\t\t}\r\n\r\n\t\t\t\t\t\t@Override\r\n\t\t\t\t\t\tpublic void onItemClickListen" +
                    "er(View v, int pos) {\r\n\t\t\t\t\t\t\t");
            
            #line 167 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("ViewModel  ");
            
            #line 167 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("=");
            
            #line 167 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("Adapter.getItem(pos);\r\n\t\t\t\t\t\t\t//ToastUtil.Show(_context,");
            
            #line 168 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write(".toString());\r\n\t\t\t\t\t\t\tFragmentTransaction ");
            
            #line 169 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("Transaction = _manage.beginTransaction();\r\n\t\t\t\t\t\t\tBundle ");
            
            #line 170 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("Bundle=new Bundle();\r\n\t\t\t\t\t\t\t");
            
            #line 171 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("Bundle.put");
            
            #line 171 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PKData.CodeType.Substring(0, 1).ToUpper() +PKData.CodeType.Substring(1).ToLower()));
            
            #line default
            #line hidden
            this.Write("(\"");
            
            #line 171 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PKData.Code));
            
            #line default
            #line hidden
            this.Write("\",");
            
            #line 171 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write(".get");
            
            #line 171 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            
            #line 171 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PKData.Code));
            
            #line default
            #line hidden
            this.Write("());\r\n\t\t\t\t\t\t\t");
            
            #line 172 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("Transaction.replace(R.id.content,\r\n\t\t\t\t\t\t\t");
            
            #line 173 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("Fragment.newInstance(");
            
            #line 173 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("Bundle), \"");
            
            #line 173 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("\").addToBackStack(\"");
            
            #line 173 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("\").commitAllowingStateLoss();\r\n\t\t\t\t\t\t}\r\n\t\t\t\t\t});\r\n\t\t\t}\r\n\t\t\telse\r\n\t\t\t{\r\n\t\t\t\t_subsc" +
                    "riptions.add(new ");
            
            #line 179 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("Service(_context, _loading).GetList(IsDescending,OrderBy,Page,PageCount).subscrib" +
                    "e(new MySubscriber<Msg<PageList<");
            
            #line 179 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("Model>>>(_context, _loading) {\r\n                    @Override\r\n                  " +
                    "  public void onNext(Msg<PageList<");
            
            #line 181 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write(@"Model>> pageListMsg) {
						if (!pageListMsg.Status) 
						{
							ToastUtil.Show(_context,pageListMsg.Msg);
							return;
						}
						if(Page==1){
							TotalCount=pageListMsg.Object.TotalCount;
							TotalPage=pageListMsg.Object.TotalPage;
							ToastUtil.Show(_context, ""总条数:""+pageListMsg.Object.TotalCount+""总页数:""+pageListMsg.Object.TotalPage);
						}
                        List<");
            
            #line 192 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("ViewModel> ");
            
            #line 192 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write(" = new ArrayList<>();\r\n                        for (");
            
            #line 193 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("Model item : pageListMsg.Object.Records) {\r\n                            ");
            
            #line 194 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write(".add(item.get");
            
            #line 194 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("ViewModel());\r\n                        }\r\n                        final Recycle");
            
            #line 196 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("Adapter ");
            
            #line 196 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("Adapter = new Recycle");
            
            #line 196 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("Adapter(");
            
            #line 196 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write(");\r\n                        _binding.DataView.setAdapter(");
            
            #line 197 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("Adapter);\r\n\t\t\t\t\t\t");
            
            #line 198 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("Adapter.setOnItemActionListener(new Recycle");
            
            #line 198 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("Adapter.OnItemActionListener() {\r\n\t\t\t\t\t\t\t@Override\r\n\t\t\t\t\t\t\tpublic boolean onItemL" +
                    "ongClickListener(View v, int pos) {\r\n\t\t\t\t\t\t\t\tBundle myDialogBundle=new Bundle();" +
                    "\r\n\t\t\t\t\t\t\t\tmyDialogBundle.putInt(\"position\",pos);\r\n\t\t\t\t\t\t\t\t");
            
            #line 203 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("ViewModel  ");
            
            #line 203 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("=");
            
            #line 203 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("Adapter.getItem(pos);\r\n\t\t\t\t\t\t\t\tmyDialogBundle.put");
            
            #line 204 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PKData.CodeType.Substring(0, 1).ToUpper() +PKData.CodeType.Substring(1).ToLower()));
            
            #line default
            #line hidden
            this.Write("(\"");
            
            #line 204 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PKData.Code));
            
            #line default
            #line hidden
            this.Write("\",");
            
            #line 204 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write(".get");
            
            #line 204 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            
            #line 204 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PKData.Code));
            
            #line default
            #line hidden
            this.Write("());\r\n\t\t\t\t\t\t\t\t_mydialog.setBundle(myDialogBundle);\r\n\t\t\t\t\t\t\t\t_mydialog.Show();\r\n\t\t" +
                    "\t\t\t\t\t\treturn true;\r\n\t\t\t\t\t\t\t}\r\n\r\n\t\t\t\t\t\t\t@Override\r\n\t\t\t\t\t\t\tpublic void onItemClick" +
                    "Listener(View v, int pos) {\r\n\t\t\t\t\t\t\t\t");
            
            #line 212 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("ViewModel  ");
            
            #line 212 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("=");
            
            #line 212 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("Adapter.getItem(pos);\r\n\t\t\t\t\t\t\t\t//ToastUtil.Show(_context,");
            
            #line 213 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write(".toString());\r\n\t\t\t\t\t\t\t\tFragmentTransaction ");
            
            #line 214 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("Transaction = _manage.beginTransaction();\r\n\t\t\t\t\t\t\t\tBundle ");
            
            #line 215 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("Bundle=new Bundle();\r\n\t\t\t\t\t\t\t\t");
            
            #line 216 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("Bundle.put");
            
            #line 216 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PKData.CodeType.Substring(0, 1).ToUpper() +PKData.CodeType.Substring(1).ToLower()));
            
            #line default
            #line hidden
            this.Write("(\"");
            
            #line 216 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PKData.Code));
            
            #line default
            #line hidden
            this.Write("\",");
            
            #line 216 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write(".get");
            
            #line 216 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            
            #line 216 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PKData.Code));
            
            #line default
            #line hidden
            this.Write("());\r\n\t\t\t\t\t\t\t\t");
            
            #line 217 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("Transaction.replace(R.id.content,\r\n\t\t\t\t\t\t\t\t");
            
            #line 218 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("Fragment.newInstance(");
            
            #line 218 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("Bundle), \"");
            
            #line 218 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("\").addToBackStack(\"");
            
            #line 218 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("\").commitAllowingStateLoss();\r\n\t\t\t\t\t\t\t}\r\n\t\t\t\t\t\t});\r\n                    }\r\n      " +
                    "          }));\r\n\t\t\t}\r\n            break;\r\n");
            
            #line 225 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write(@"        }
	}

    
	private View.OnClickListener deletelistener=new View.OnClickListener() {
        @Override
        public void onClick(View v) {
			_mydialog.Dismiss();
            switch (v.getId()){
                case R.id.MyDialog_SureText:
				final Bundle myDialogBundle=_mydialog.getBundle();
				MySubscriber mySubscriber=new MySubscriber<Msg<Object>>(_context, _loading) {
                    @Override
                    public void onNext(Msg<Object> Msg) {
						if(Msg.Status)
						{
						switch (ClickID) {
");
            
            #line 243 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
foreach(var item in _models){
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 245 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
 var PKData=item.ColumnsList.Where(t=>t.PK==true).FirstOrDefault();
	if(PKData==null) throw new Exception("未包含主键字段");

            
            #line default
            #line hidden
            this.Write("\t\t\t\tcase R.id.");
            
            #line 248 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("_List:\r\n\t\t\t\t\tRecycle");
            
            #line 249 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("Adapter ");
            
            #line 249 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("Adapter = (Recycle");
            
            #line 249 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("Adapter)_binding.DataView.getAdapter();\r\n\t\t\t\t\tList<");
            
            #line 250 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("ViewModel> ");
            
            #line 250 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("=");
            
            #line 250 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("Adapter.getData();\r\n\t\t\t\t\t");
            
            #line 251 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write(".remove(myDialogBundle.getInt(\"position\"));\r\n\t\t\t\t\t");
            
            #line 252 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("Adapter.setData(");
            
            #line 252 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write(");\r\n\t\t\t\t\tbreak;\r\n");
            
            #line 254 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t}\r\n\t\t\t\t\t\tToastUtil.Show(_context, Msg.Msg);\r\n                    }\r\n\t\t\t\t\t}\r" +
                    "\n                };\r\n\t\t\t\tswitch (ClickID) {\r\n");
            
            #line 261 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
foreach(var item in _models){
            
            #line default
            #line hidden
            
            #line 262 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
 var PKData=item.ColumnsList.Where(t=>t.PK==true).FirstOrDefault();
	if(PKData==null) throw new Exception("未包含主键字段");

            
            #line default
            #line hidden
            this.Write("\t\t\t\tcase R.id.");
            
            #line 265 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("_List:\r\n\t\t\t\t\t");
            
            #line 266 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PKData.CodeType=="string"?"String":PKData.CodeType));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 266 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("=myDialogBundle.get");
            
            #line 266 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PKData.CodeType.Substring(0, 1).ToUpper() +PKData.CodeType.Substring(1).ToLower()));
            
            #line default
            #line hidden
            this.Write("(\"");
            
            #line 266 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PKData.Code));
            
            #line default
            #line hidden
            this.Write("\");\r\n\t\t\t\t\tList<");
            
            #line 267 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PKData.CodeType=="string"?"String":"Integer"));
            
            #line default
            #line hidden
            this.Write("> ");
            
            #line 267 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("List=new ArrayList();\r\n\t\t\t\t\t");
            
            #line 268 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("List.add(");
            
            #line 268 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write(");\r\n\t\t\t\t\tnew ");
            
            #line 269 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("Service(_context, _loading).RemoveList(");
            
            #line 269 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("List).subscribe(mySubscriber);\r\n\t\t\t\tbreak;\r\n");
            
            #line 271 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write(@"				}
				break;
                case R.id.MyDialog_ChanelText:
				
				break;
            }
        }
    };



	private View.OnClickListener listener=new View.OnClickListener(){
        @Override
        public void onClick(View v) {
            if(v.getId()==R.id.Data_Add) {
				switch (ClickID) {
");
            
            #line 288 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
foreach(var item in _models){
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\tcase R.id.");
            
            #line 289 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("_List:\r\n");
            
            #line 290 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
 if(item.Code=="Action") {
            
            #line default
            #line hidden
            this.Write(@"						_subscriptions.add(_actionService.Init().subscribe(new MySubscriber<Msg<Object>>(_context, true, _loading) {
                            @Override
                            public void onNext(Msg<Object> msg) {
                                if (msg.Status) {
                                    ToastUtil.Show(_context, msg.Msg);
                                } else {
                                    ToastUtil.Show(_context, msg.Msg);
                                }
                            }
                        }));
						break;
");
            
            #line 302 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
}else{
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\tFragmentTransaction ");
            
            #line 303 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("Transaction = _manage.beginTransaction();\r\n\t\t\t\t\t\t");
            
            #line 304 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("Transaction.replace(R.id.content,\r\n\t\t\t\t\t\t");
            
            #line 305 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("Fragment.newInstance(), \"");
            
            #line 305 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("\").addToBackStack(\"");
            
            #line 305 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("\").commitAllowingStateLoss();\r\n\t\t\t\t\t\tbreak;\r\n");
            
            #line 307 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
}}
            
            #line default
            #line hidden
            this.Write(@"				}
			}
        }
    };

	private RecyclerView.OnScrollListener liser=new RecyclerView.OnScrollListener() {
		@Override
		public void onScrollStateChanged(RecyclerView recyclerView, int newState) {
			super.onScrollStateChanged(recyclerView, newState);
			int currentCount = 0;
			if (_LayoutManager instanceof LinearLayoutManager) {
				currentCount = ((LinearLayoutManager) _LayoutManager).findLastVisibleItemPosition() + 1;
			} else if (_LayoutManager instanceof StaggeredGridLayoutManager) {
				int[] lastVisibleItemPositions = ((StaggeredGridLayoutManager) _LayoutManager).findLastVisibleItemPositions(null);
				Arrays.sort(lastVisibleItemPositions);
				currentCount = lastVisibleItemPositions[lastVisibleItemPositions.length - 1] + 1;
			}
			int itemCount = _binding.DataView.getAdapter().getItemCount();
			if (TotalPage>Page&&!isLoading && newState == RecyclerView.SCROLL_STATE_IDLE
					&& currentCount == itemCount) {
				Page++;
				_binding.LoadingMore.setVisibility(View.VISIBLE);
				LoadingData();
			}
		}
	};

	private SwipeRefreshLayout.OnRefreshListener RefreshListener= new SwipeRefreshLayout.OnRefreshListener() {
		@Override
		public void onRefresh() {
			Page=1;
			LoadingData();
		}
	};
	private void LoadingData(){
		isLoading=true;
		switch (ClickID) {
");
            
            #line 345 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
foreach(var item in _models){
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\tcase R.id.");
            
            #line 346 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("_List:\r\n\t\t\t\t\t\t\t_subscriptions.add(new ");
            
            #line 347 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("Service(_context, null).GetList(IsDescending,OrderBy,Page,PageCount).subscribe(ne" +
                    "w Subscriber<Msg<PageList<");
            
            #line 347 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write(@"Model>>>() {
								@Override
								public void onCompleted() {
									isLoading = false;
								}

								@Override
								public void onError(Throwable e) {
									isLoading = false;
									if(Page==1)
										_binding.DataRefresh.setRefreshing(false);
									else
										_binding.LoadingMore.setVisibility(View.GONE);
								}
								@Override
								public void onNext(Msg<PageList<");
            
            #line 362 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("Model>> pageListMsg) {\r\n\t\t\t\t\t\t\t\t\tisLoading=false;\r\n\t\t\t\t\t\t\t\t\tif (!pageListMsg.Stat" +
                    "us) \r\n\t\t\t\t\t\t\t\t\t{\r\n\t\t\t\t\t\t\t\t\t\tToastUtil.Show(_context,pageListMsg.Msg);\r\n\t\t\t\t\t\t\t\t\t" +
                    "\treturn;\r\n\t\t\t\t\t\t\t\t\t}\r\n\t\t\t\t\t\t\t\t\tRecycle");
            
            #line 369 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("Adapter ");
            
            #line 369 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("Adapter = (Recycle");
            
            #line 369 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("Adapter)_binding.DataView.getAdapter();\r\n\t\t\t\t\t\t\t\t\tList<");
            
            #line 370 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("ViewModel> ");
            
            #line 370 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write(" ;\r\n\t\t\t\t\t\t\t\t\tif(Page==1)\r\n\t\t\t\t\t\t\t\t\t\t");
            
            #line 372 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("= new ArrayList<>();\r\n\t\t\t\t\t\t\t\t\telse\r\n\t\t\t\t\t\t\t\t\t{\r\n\t\t\t\t\t\t\t\t\t\t");
            
            #line 375 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("=");
            
            #line 375 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("Adapter.getData();\r\n\t\t\t\t\t\t\t\t\t}\r\n\t\t\t\t\t\t\t\t\tfor (");
            
            #line 377 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("Model item : pageListMsg.Object.Records) {\r\n\t\t\t\t\t\t\t\t\t\t");
            
            #line 378 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write(".add(item.get");
            
            #line 378 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("ViewModel());\r\n\t\t\t\t\t\t\t\t\t}\r\n\t\t\t\t\t\t\t\t\t");
            
            #line 380 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("Adapter.setData( ");
            
            #line 380 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write(@");
									if(Page==1){
										_binding.DataRefresh.setRefreshing(false);
										TotalCount=pageListMsg.Object.TotalCount;
										TotalPage=pageListMsg.Object.TotalPage;
										ToastUtil.Show(_context, ""总条数:""+pageListMsg.Object.TotalCount+""总页数:""+pageListMsg.Object.TotalPage);
									}
									else
									{
										_binding.LoadingMore.setVisibility(View.GONE);
									}
								}
							}));
						break;
");
            
            #line 394 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_DataViewMainEventTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("\t\t\t\t}\r\n\t}\r\n}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public class J_DataViewMainEventTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
