// ------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本: 16.0.0.0
//  
//     对此文件的更改可能导致不正确的行为，如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace FileLoder.T_Android
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_LayoutItemTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class J_LayoutItemTemplate : J_LayoutItemTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("<?xml version=\"1.0\" encoding=\"utf-8\"?>\r\n<layout xmlns:android=\"http://schemas.and" +
                    "roid.com/apk/res/android\"\r\n    xmlns:bind=\"http://schemas.android.com/apk/res-au" +
                    "to\">\r\n    <data>\r\n\t\t<import type=\"");
            
            #line 10 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_LayoutItemTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_package));
            
            #line default
            #line hidden
            this.Write(".Common.Util\" />\r\n        <variable name=\"");
            
            #line 11 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_LayoutItemTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityName));
            
            #line default
            #line hidden
            this.Write("Model\" type=\"");
            
            #line 11 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_LayoutItemTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_package));
            
            #line default
            #line hidden
            this.Write(".ViewModel.");
            
            #line 11 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_LayoutItemTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityName));
            
            #line default
            #line hidden
            this.Write("ViewModel\"/>\r\n        <!--<variable name=\"item_");
            
            #line 12 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_LayoutItemTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityName));
            
            #line default
            #line hidden
            this.Write("Event\" type=\"");
            
            #line 12 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_LayoutItemTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_package));
            
            #line default
            #line hidden
            this.Write(".Event.item_");
            
            #line 12 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_LayoutItemTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityName));
            
            #line default
            #line hidden
            this.Write("Event\"/> -->\r\n\t\t<!--android:onClick=\"@{");
            
            #line 13 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_LayoutItemTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityName));
            
            #line default
            #line hidden
            this.Write("Adapter.");
            
            #line 13 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_LayoutItemTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_models.Code));
            
            #line default
            #line hidden
            this.Write("_Liser}\"-->\r\n\t\t<!--<variable name=\"");
            
            #line 14 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_LayoutItemTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityName));
            
            #line default
            #line hidden
            this.Write("Adapter\" type=\"");
            
            #line 14 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_LayoutItemTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_package));
            
            #line default
            #line hidden
            this.Write(".Adapter.");
            
            #line 14 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_LayoutItemTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityName));
            
            #line default
            #line hidden
            this.Write("Adapter\" />-->\r\n    </data>\r\n<android.support.v7.widget.CardView\r\n    android:id=" +
                    "\"@+id/");
            
            #line 17 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_LayoutItemTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityName));
            
            #line default
            #line hidden
            this.Write(@"_ItemCardView""
    android:layout_margin=""5dp""
    android:layout_height=""wrap_content""
    bind:cardBackgroundColor=""@android:color/white""
    bind:cardCornerRadius=""5dp""
    bind:cardElevation=""5dp""
    bind:contentPadding=""5dip""
    android:layout_width=""match_parent""
	 >
<RelativeLayout
    android:layout_width=""match_parent""
    android:layout_height=""wrap_content""
    >
");
            
            #line 30 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_LayoutItemTemplate.tt"

	var blowID="";
	foreach(var item in _models.ColumnsList.Where(t=>t.Virtual==false)){
	var Code=_entityName+item.Code;

            
            #line default
            #line hidden
            this.Write("\t\t<TextView\r\n        android:id=\"@+id/item_");
            
            #line 36 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_LayoutItemTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityName));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 36 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_LayoutItemTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Code.Replace("?","")));
            
            #line default
            #line hidden
            this.Write("\"\r\n        android:layout_width=\"match_parent\"\r\n        android:layout_height=\"wr" +
                    "ap_content\"\r\n");
            
            #line 39 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_LayoutItemTemplate.tt"
 if(blowID.Trim()!=""){
            
            #line default
            #line hidden
            this.Write("\t\tandroid:layout_below=\"@+id/");
            
            #line 40 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_LayoutItemTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(blowID));
            
            #line default
            #line hidden
            this.Write("\"\r\n");
            
            #line 41 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_LayoutItemTemplate.tt"
 blowID="item_"+_entityName+"_"+item.Code.Replace("?",""); }else {
		blowID="item_"+_entityName+"_"+item.Code.Replace("?","");
}	if(item.PK){
            
            #line default
            #line hidden
            this.Write("\t\t\tandroid:visibility=\"gone\"\r\n");
            
            #line 45 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_LayoutItemTemplate.tt"
} if(item.EM){
            
            #line default
            #line hidden
            this.Write("        android:text=\"@{");
            
            #line 46 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_LayoutItemTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityName));
            
            #line default
            #line hidden
            this.Write("Model.");
            
            #line 46 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_LayoutItemTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Code.Substring(0, 1).ToLower() + Code.Substring(1).Replace("?","")+"String"));
            
            #line default
            #line hidden
            this.Write("}\"/>\r\n");
            
            #line 47 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_LayoutItemTemplate.tt"
}else if(item.CodeType=="DateTime"){
            
            #line default
            #line hidden
            this.Write("\t\tandroid:text=\"@{Util.ToDate(String.valueOf(");
            
            #line 48 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_LayoutItemTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityName));
            
            #line default
            #line hidden
            this.Write("Model.");
            
            #line 48 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_LayoutItemTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Code.Substring(0, 1).ToLower() + Code.Substring(1).Replace("?","")));
            
            #line default
            #line hidden
            this.Write("))}\"/>\r\n");
            
            #line 49 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_LayoutItemTemplate.tt"
}else{
            
            #line default
            #line hidden
            this.Write("\t\r\n\t\tandroid:text=\"@{String.valueOf(");
            
            #line 51 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_LayoutItemTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityName));
            
            #line default
            #line hidden
            this.Write("Model.");
            
            #line 51 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_LayoutItemTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Code.Substring(0, 1).ToLower() + Code.Substring(1).Replace("?","")));
            
            #line default
            #line hidden
            this.Write(")}\"/>\r\n");
            
            #line 52 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_Android\J_LayoutItemTemplate.tt"
}}
            
            #line default
            #line hidden
            this.Write("</RelativeLayout>\r\n</android.support.v7.widget.CardView>\r\n</layout>\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public class J_LayoutItemTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
