// ------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本: 16.0.0.0
//  
//     对此文件的更改可能导致不正确的行为，如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace FileLoder.T_AdoNet
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\NewIServiceTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class NewIServiceTemplate : NewIServiceTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("using System.Linq;\r\nusing ");
            
            #line 7 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\NewIServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_projectName));
            
            #line default
            #line hidden
            this.Write(".Model;\r\nusing System.Collections.Generic;\r\nusing System.Data.SqlClient;\r\nusing S" +
                    "ystem.Data;\r\nusing System;\r\n\r\nnamespace ");
            
            #line 13 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\NewIServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_projectName));
            
            #line default
            #line hidden
            this.Write(".IDAL.");
            
            #line 13 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\NewIServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityName));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n");
            
            #line 15 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\NewIServiceTemplate.tt"
 var PKData=_Columns.Where(t=>t.PK==true).FirstOrDefault();
if(PKData==null) throw new Exception("未包含主键字段");
            
            #line default
            #line hidden
            this.Write("\t/// <summary>\r\n\t/// ");
            
            #line 18 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\NewIServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityName));
            
            #line default
            #line hidden
            this.Write("操作接口方法\r\n\t/// </summary>\r\n\tpublic interface I");
            
            #line 20 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\NewIServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityName));
            
            #line default
            #line hidden
            this.Write("DAL \r\n\t{\r\n");
            
            #line 22 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\NewIServiceTemplate.tt"
if(PKData.IsAutoAdd){
            
            #line default
            #line hidden
            this.Write("\t\t/// <summary>\r\n\t\t/// 得到最大ID\r\n\t\t/// </summary>\r\n\t\t");
            
            #line 26 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\NewIServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PKData.CodeType));
            
            #line default
            #line hidden
            this.Write(" GetMaxId();\r\n");
            
            #line 27 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\NewIServiceTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("\t\t/// <summary>\r\n\t\t/// 是否存在该记录\r\n\t\t/// </summary>\r\n\t\tbool Exists(");
            
            #line 31 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\NewIServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PKData.CodeType));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 31 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\NewIServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PKData.Code));
            
            #line default
            #line hidden
            this.Write(");\r\n\t\t/// <summary>\r\n\t\t/// 新增\r\n\t\t/// </summary>\r\n\t\t");
            
            #line 35 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\NewIServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PKData.IsAutoAdd?PKData.CodeType:"bool"));
            
            #line default
            #line hidden
            this.Write(" Add(");
            
            #line 35 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\NewIServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityName));
            
            #line default
            #line hidden
            this.Write("Model  m");
            
            #line 35 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\NewIServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityName.ToLower()));
            
            #line default
            #line hidden
            this.Write(");\r\n\t\t/// <summary>\r\n\t\t/// 删除\r\n\t\t/// </summary>\r\n\t\tbool Delete(");
            
            #line 39 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\NewIServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PKData.CodeType));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 39 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\NewIServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PKData.Code));
            
            #line default
            #line hidden
            this.Write(");\r\n\t\t/// <summary>\r\n\t\t/// 删除\r\n\t\t/// </summary>\r\n\t\tbool Delete(string Where=null," +
                    " List<SqlParameter> para = null);\r\n\t\t/// <summary>\r\n\t\t/// 更新\r\n\t\t/// </summary>\r\n" +
                    "\t\tbool Update(");
            
            #line 47 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\NewIServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityName));
            
            #line default
            #line hidden
            this.Write("Model  m");
            
            #line 47 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\NewIServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityName.ToLower()));
            
            #line default
            #line hidden
            this.Write(");\r\n\t\t/// <summary>\r\n\t\t/// 根据主键查询\r\n\t\t/// </summary>\r\n\t\t");
            
            #line 51 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\NewIServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityName));
            
            #line default
            #line hidden
            this.Write("Model GetModel(");
            
            #line 51 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\NewIServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PKData.CodeType));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 51 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\NewIServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PKData.Code));
            
            #line default
            #line hidden
            this.Write(@");
		
		/// <summary>
		/// 获得数据列表
		/// </summary>
		DataSet GetList(string Where=null, List<SqlParameter> para = null);

		/// <summary>
		/// 获得前几行数据
		/// </summary>
        DataSet GetList(int Top, string strWhere, string filedOrder, List<SqlParameter> para = null);
		/// <summary>
        /// 获取记录总数
        /// </summary>
		int GetRecordCount(string strWhere=null, List<SqlParameter> para = null);
		/// <summary>
		/// 模型转换
		/// </summary>
		");
            
            #line 69 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\NewIServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityName));
            
            #line default
            #line hidden
            this.Write("Model RowToModel(DataRow row);\r\n\r\n\t\t/// <summary>\r\n\t\t/// where查询\r\n\t\t/// </summary" +
                    ">\r\n\t\tList<");
            
            #line 74 "E:\JiTuan_Project\TepCloud\DotNetCode\Current\FileLoder\T_AdoNet\NewIServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityName));
            
            #line default
            #line hidden
            this.Write(@"Model> GetModelList(string Where=null, List<SqlParameter> para = null);
		/// <summary>
		/// 分页获取数据列表
		/// </summary>
        DataSet GetListByPage(string strWhere, string orderby, int startIndex, int endIndex, List<SqlParameter> para = null);
	}
}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public class NewIServiceTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
